/* eslint-disable import/prefer-default-export, import/no-cycle */
import {
  Account,
  AccountCoverage,
  AccountGuarantor,
  AccountStatus,
  ActionCardinalityBehavior,
  ActionConditionKind,
  ActionGroupingBehavior,
  ActionParticipantType,
  ActionPrecheckBehavior,
  ActionRelationshipType,
  ActionRequiredBehavior,
  ActionSelectionBehavior,
  ActivityDefinition,
  ActivityDefinitionDynamicValue,
  ActivityDefinitionParticipant,
  ActivityDefinitionKind,
  ActivityParticipantType,
  Address,
  AddressType,
  AddressUse,
  AdministrativeGender,
  AdverseEvent,
  AdverseEventSuspectEntity,
  AdverseEventSuspectEntityCausality,
  AdverseEventActuality,
  Age,
  AggregationMode,
  AllergyIntolerance,
  AllergyIntoleranceReaction,
  AllergyIntoleranceCategory,
  AllergyIntoleranceCriticality,
  AllergyIntoleranceSeverity,
  AllergyIntoleranceType,
  Annotation,
  Appointment,
  AppointmentParticipant,
  AppointmentResponse,
  AppointmentStatus,
  AssertionDirectionType,
  AssertionOperatorType,
  AssertionResponseTypes,
  Attachment,
  AuditEvent,
  AuditEventAgent,
  AuditEventAgentNetwork,
  AuditEventEntity,
  AuditEventEntityDetail,
  AuditEventSource,
  AuditEventAction,
  AuditEventAgentNetworkType,
  AuditEventOutcome,
  BackboneElement,
  Basic,
  Binary,
  BindingStrength,
  BiologicallyDerivedProduct,
  BiologicallyDerivedProductCollection,
  BiologicallyDerivedProductManipulation,
  BiologicallyDerivedProductProcessing,
  BiologicallyDerivedProductStorage,
  BiologicallyDerivedProductCategory,
  BiologicallyDerivedProductStatus,
  BiologicallyDerivedProductStorageScale,
  BodyStructure,
  Bundle,
  BundleEntry,
  BundleEntryRequest,
  BundleEntryResponse,
  BundleEntrySearch,
  BundleLink,
  BundleType,
  CapabilityStatement,
  CapabilityStatementDocument,
  CapabilityStatementImplementation,
  CapabilityStatementMessaging,
  CapabilityStatementMessagingEndpoint,
  CapabilityStatementMessagingSupportedMessage,
  CapabilityStatementRest,
  CapabilityStatementRestInteraction,
  CapabilityStatementRestResource,
  CapabilityStatementRestResourceInteraction,
  CapabilityStatementRestResourceOperation,
  CapabilityStatementRestResourceSearchParam,
  CapabilityStatementRestSecurity,
  CapabilityStatementSoftware,
  CapabilityStatementKind,
  CarePlan,
  CarePlanActivity,
  CarePlanActivityDetail,
  CarePlanActivityKind,
  CarePlanActivityStatus,
  CarePlanIntent,
  CarePlanStatus,
  CareTeam,
  CareTeamParticipant,
  CareTeamStatus,
  CatalogEntry,
  CatalogEntryRelatedEntry,
  CatalogEntryRelationType,
  ChargeItem,
  ChargeItemPerformer,
  ChargeItemDefinition,
  ChargeItemDefinitionApplicability,
  ChargeItemDefinitionPropertyGroup,
  ChargeItemDefinitionPropertyGroupPriceComponent,
  ChargeItemDefinitionPriceComponentType,
  ChargeItemStatus,
  Claim,
  ClaimAccident,
  ClaimCareTeam,
  ClaimDiagnosis,
  ClaimInsurance,
  ClaimItem,
  ClaimItemDetail,
  ClaimItemDetailSubDetail,
  ClaimPayee,
  ClaimProcedure,
  ClaimRelated,
  ClaimSupportingInfo,
  ClaimResponse,
  ClaimResponseAddItem,
  ClaimResponseAddItemDetail,
  ClaimResponseAddItemDetailSubDetail,
  ClaimResponseError,
  ClaimResponseInsurance,
  ClaimResponseItem,
  ClaimResponseItemAdjudication,
  ClaimResponseItemDetail,
  ClaimResponseItemDetailSubDetail,
  ClaimResponsePayment,
  ClaimResponseProcessNote,
  ClaimResponseTotal,
  ClaimResponseStatus,
  ClaimStatus,
  ClinicalImpression,
  ClinicalImpressionFinding,
  ClinicalImpressionInvestigation,
  ClinicalImpressionStatus,
  CodeSearchSupport,
  CodeSystem,
  CodeSystemConcept,
  CodeSystemConceptDesignation,
  CodeSystemConceptProperty,
  CodeSystemFilter,
  CodeSystemProperty,
  CodeSystemContentMode,
  CodeSystemHierarchyMeaning,
  CodeableConcept,
  Coding,
  Communication,
  CommunicationPayload,
  CommunicationPriority,
  CommunicationRequest,
  CommunicationRequestPayload,
  CommunicationRequestStatus,
  CommunicationStatus,
  CompartmentCode,
  CompartmentDefinition,
  CompartmentDefinitionResource,
  CompartmentType,
  Composition,
  CompositionAttester,
  CompositionEvent,
  CompositionRelatesTo,
  CompositionSection,
  CompositionAttestationMode,
  CompositionStatus,
  ConceptMap,
  ConceptMapGroup,
  ConceptMapGroupElement,
  ConceptMapGroupElementTarget,
  ConceptMapGroupElementTargetDependsOn,
  ConceptMapGroupUnmapped,
  ConceptMapEquivalence,
  ConceptMapGroupUnmappedMode,
  Condition,
  ConditionEvidence,
  ConditionStage,
  ConditionalDeleteStatus,
  ConditionalReadStatus,
  Consent,
  ConsentPolicy,
  ConsentProvision,
  ConsentProvisionActor,
  ConsentProvisionData,
  ConsentVerification,
  ConsentDataMeaning,
  ConsentProvisionType,
  ConsentState,
  ConstraintSeverity,
  ContactDetail,
  ContactPoint,
  ContactPointSystem,
  ContactPointUse,
  Contract,
  ContractContentDefinition,
  ContractFriendly,
  ContractLegal,
  ContractRule,
  ContractSigner,
  ContractTerm,
  ContractTermAction,
  ContractTermActionSubject,
  ContractTermAsset,
  ContractTermAssetContext,
  ContractTermAssetValuedItem,
  ContractTermOffer,
  ContractTermOfferAnswer,
  ContractTermOfferParty,
  ContractTermSecurityLabel,
  ContractPublicationStatus,
  ContractStatus,
  Contributor,
  ContributorType,
  Count,
  Coverage,
  CoverageClass,
  CoverageCostToBeneficiary,
  CoverageCostToBeneficiaryException,
  CoverageEligibilityRequest,
  CoverageEligibilityRequestInsurance,
  CoverageEligibilityRequestItem,
  CoverageEligibilityRequestItemDiagnosis,
  CoverageEligibilityRequestSupportingInfo,
  CoverageEligibilityResponse,
  CoverageEligibilityResponseError,
  CoverageEligibilityResponseInsurance,
  CoverageEligibilityResponseInsuranceItem,
  CoverageEligibilityResponseInsuranceItemBenefit,
  CoverageStatus,
  CurrencyCode,
  DataRequirement,
  DataRequirementCodeFilter,
  DataRequirementDateFilter,
  DataRequirementSort,
  DayOfWeek,
  DaysOfWeek,
  DetectedIssue,
  DetectedIssueEvidence,
  DetectedIssueMitigation,
  DetectedIssueSeverity,
  DetectedIssueStatus,
  Device,
  DeviceDeviceName,
  DeviceProperty,
  DeviceSpecialization,
  DeviceUdiCarrier,
  DeviceVersion,
  DeviceDefinition,
  DeviceDefinitionCapability,
  DeviceDefinitionDeviceName,
  DeviceDefinitionMaterial,
  DeviceDefinitionProperty,
  DeviceDefinitionSpecialization,
  DeviceDefinitionUdiDeviceIdentifier,
  DeviceMetric,
  DeviceMetricCalibration,
  DeviceMetricCalibrationState,
  DeviceMetricCalibrationType,
  DeviceMetricCategory,
  DeviceMetricColor,
  DeviceMetricOperationalStatus,
  DeviceNameType,
  DeviceRequest,
  DeviceRequestParameter,
  DeviceRequestStatus,
  DeviceUseStatement,
  DeviceUseStatementStatus,
  DiagnosticReport,
  DiagnosticReportMedia,
  DiagnosticReportStatus,
  DiscriminatorType,
  Distance,
  DocumentConfidentiality,
  DocumentManifest,
  DocumentManifestRelated,
  DocumentMode,
  DocumentReference,
  DocumentReferenceContent,
  DocumentReferenceContext,
  DocumentReferenceRelatesTo,
  DocumentReferenceStatus,
  DocumentRelationshipType,
  DomainResource,
  Dosage,
  DosageDoseAndRate,
  Duration,
  EffectEvidenceSynthesis,
  EffectEvidenceSynthesisCertainty,
  EffectEvidenceSynthesisCertaintyCertaintySubcomponent,
  EffectEvidenceSynthesisEffectEstimate,
  EffectEvidenceSynthesisEffectEstimatePrecisionEstimate,
  EffectEvidenceSynthesisResultsByExposure,
  EffectEvidenceSynthesisSampleSize,
  Element,
  ElementDefinition,
  ElementDefinitionBase,
  ElementDefinitionBinding,
  ElementDefinitionConstraint,
  ElementDefinitionExample,
  ElementDefinitionMapping,
  ElementDefinitionSlicing,
  ElementDefinitionSlicingDiscriminator,
  ElementDefinitionType,
  EligibilityRequestPurpose,
  EligibilityRequestStatus,
  EligibilityResponsePurpose,
  EligibilityResponseStatus,
  EnableWhenBehavior,
  Encounter,
  EncounterClassHistory,
  EncounterDiagnosis,
  EncounterHospitalization,
  EncounterLocation,
  EncounterParticipant,
  EncounterStatusHistory,
  EncounterLocationStatus,
  EncounterStatus,
  Endpoint,
  EndpointStatus,
  EnrollmentRequest,
  EnrollmentRequestStatus,
  EnrollmentResponse,
  EnrollmentResponseStatus,
  EpisodeOfCare,
  EpisodeOfCareDiagnosis,
  EpisodeOfCareStatusHistory,
  EpisodeOfCareStatus,
  EventCapabilityMode,
  EventDefinition,
  EventTiming,
  Evidence,
  EvidenceVariable,
  EvidenceVariableCharacteristic,
  EvidenceVariableType,
  ExampleScenario,
  ExampleScenarioActor,
  ExampleScenarioInstance,
  ExampleScenarioInstanceContainedInstance,
  ExampleScenarioInstanceVersion,
  ExampleScenarioProcess,
  ExampleScenarioProcessStep,
  ExampleScenarioProcessStepAlternative,
  ExampleScenarioProcessStepOperation,
  ExampleScenarioActorType,
  ExplanationOfBenefit,
  ExplanationOfBenefitAccident,
  ExplanationOfBenefitAddItem,
  ExplanationOfBenefitAddItemDetail,
  ExplanationOfBenefitAddItemDetailSubDetail,
  ExplanationOfBenefitBenefitBalance,
  ExplanationOfBenefitBenefitBalanceFinancial,
  ExplanationOfBenefitCareTeam,
  ExplanationOfBenefitDiagnosis,
  ExplanationOfBenefitInsurance,
  ExplanationOfBenefitItem,
  ExplanationOfBenefitItemAdjudication,
  ExplanationOfBenefitItemDetail,
  ExplanationOfBenefitItemDetailSubDetail,
  ExplanationOfBenefitPayee,
  ExplanationOfBenefitPayment,
  ExplanationOfBenefitProcedure,
  ExplanationOfBenefitProcessNote,
  ExplanationOfBenefitRelated,
  ExplanationOfBenefitSupportingInfo,
  ExplanationOfBenefitTotal,
  ExplanationOfBenefitStatus,
  ExposureState,
  Expression,
  Extension,
  ExtensionContextType,
  FHIRAllTypes,
  FHIRDefinedType,
  FHIRDeviceStatus,
  FHIRResourceType,
  FHIRSubstanceStatus,
  FHIRVersion,
  FamilyHistoryStatus,
  FamilyMemberHistory,
  FamilyMemberHistoryCondition,
  FilterOperator,
  Flag,
  FlagStatus,
  Goal,
  GoalTarget,
  GoalLifecycleStatus,
  GraphCompartmentRule,
  GraphCompartmentUse,
  GraphDefinition,
  GraphDefinitionLink,
  GraphDefinitionLinkTarget,
  GraphDefinitionLinkTargetCompartment,
  Group,
  GroupCharacteristic,
  GroupMember,
  GroupMeasure,
  GroupType,
  GuidanceResponse,
  GuidanceResponseStatus,
  GuidePageGeneration,
  GuideParameterCode,
  HTTPVerb,
  HealthcareService,
  HealthcareServiceAvailableTime,
  HealthcareServiceEligibility,
  HealthcareServiceNotAvailable,
  HumanName,
  Identifier,
  IdentifierUse,
  IdentityAssuranceLevel,
  ImagingStudy,
  ImagingStudySeries,
  ImagingStudySeriesInstance,
  ImagingStudySeriesPerformer,
  ImagingStudyStatus,
  Immunization,
  ImmunizationEducation,
  ImmunizationPerformer,
  ImmunizationProtocolApplied,
  ImmunizationReaction,
  ImmunizationEvaluation,
  ImmunizationEvaluationStatus,
  ImmunizationRecommendation,
  ImmunizationRecommendationRecommendation,
  ImmunizationRecommendationRecommendationDateCriterion,
  ImmunizationStatus,
  ImplementationGuide,
  ImplementationGuideDefinition,
  ImplementationGuideDefinitionGrouping,
  ImplementationGuideDefinitionPage,
  ImplementationGuideDefinitionParameter,
  ImplementationGuideDefinitionResource,
  ImplementationGuideDefinitionTemplate,
  ImplementationGuideDependsOn,
  ImplementationGuideGlobal,
  ImplementationGuideManifest,
  ImplementationGuideManifestPage,
  ImplementationGuideManifestResource,
  InsurancePlan,
  InsurancePlanContact,
  InsurancePlanCoverage,
  InsurancePlanCoverageBenefit,
  InsurancePlanCoverageBenefitLimit,
  InsurancePlanPlan,
  InsurancePlanPlanGeneralCost,
  InsurancePlanPlanSpecificCost,
  InsurancePlanPlanSpecificCostBenefit,
  InsurancePlanPlanSpecificCostBenefitCost,
  Invoice,
  InvoiceLineItem,
  InvoiceLineItemPriceComponent,
  InvoiceParticipant,
  InvoicePriceComponentType,
  InvoiceStatus,
  IssueSeverity,
  IssueType,
  Library,
  LinkType,
  Linkage,
  LinkageItem,
  LinkageType,
  List,
  ListEntry,
  ListMode,
  ListStatus,
  Location,
  LocationHoursOfOperation,
  LocationPosition,
  LocationMode,
  LocationStatus,
  MarketingStatus,
  Measure,
  MeasureGroup,
  MeasureGroupPopulation,
  MeasureGroupStratifier,
  MeasureGroupStratifierComponent,
  MeasureSupplementalData,
  MeasureReport,
  MeasureReportGroup,
  MeasureReportGroupPopulation,
  MeasureReportGroupStratifier,
  MeasureReportGroupStratifierStratum,
  MeasureReportGroupStratifierStratumComponent,
  MeasureReportGroupStratifierStratumPopulation,
  MeasureReportStatus,
  MeasureReportType,
  Media,
  MediaStatus,
  Medication,
  MedicationBatch,
  MedicationIngredient,
  MedicationAdministration,
  MedicationAdministrationDosage,
  MedicationAdministrationPerformer,
  MedicationAdministrationStatus,
  MedicationDispense,
  MedicationDispensePerformer,
  MedicationDispenseSubstitution,
  MedicationDispenseStatus,
  MedicationKnowledge,
  MedicationKnowledgeAdministrationGuidelines,
  MedicationKnowledgeAdministrationGuidelinesDosage,
  MedicationKnowledgeAdministrationGuidelinesPatientCharacteristics,
  MedicationKnowledgeCost,
  MedicationKnowledgeDrugCharacteristic,
  MedicationKnowledgeIngredient,
  MedicationKnowledgeKinetics,
  MedicationKnowledgeMedicineClassification,
  MedicationKnowledgeMonitoringProgram,
  MedicationKnowledgeMonograph,
  MedicationKnowledgePackaging,
  MedicationKnowledgeRegulatory,
  MedicationKnowledgeRegulatoryMaxDispense,
  MedicationKnowledgeRegulatorySchedule,
  MedicationKnowledgeRegulatorySubstitution,
  MedicationKnowledgeRelatedMedicationKnowledge,
  MedicationKnowledgeStatus,
  MedicationRequest,
  MedicationRequestDispenseRequest,
  MedicationRequestDispenseRequestInitialFill,
  MedicationRequestSubstitution,
  MedicationRequestIntent,
  MedicationRequestPriority,
  MedicationRequestStatus,
  MedicationStatement,
  MedicationStatementStatus,
  MedicationStatus,
  MedicinalProduct,
  MedicinalProductManufacturingBusinessOperation,
  MedicinalProductName,
  MedicinalProductNameCountryLanguage,
  MedicinalProductNameNamePart,
  MedicinalProductSpecialDesignation,
  MedicinalProductAuthorization,
  MedicinalProductAuthorizationJurisdictionalAuthorization,
  MedicinalProductAuthorizationProcedure,
  MedicinalProductContraindication,
  MedicinalProductContraindicationOtherTherapy,
  MedicinalProductIndication,
  MedicinalProductIndicationOtherTherapy,
  MedicinalProductIngredient,
  MedicinalProductIngredientSpecifiedSubstance,
  MedicinalProductIngredientSpecifiedSubstanceStrength,
  MedicinalProductIngredientSpecifiedSubstanceStrengthReferenceStrength,
  MedicinalProductIngredientSubstance,
  MedicinalProductInteraction,
  MedicinalProductInteractionInteractant,
  MedicinalProductManufactured,
  MedicinalProductPackaged,
  MedicinalProductPackagedBatchIdentifier,
  MedicinalProductPackagedPackageItem,
  MedicinalProductPharmaceutical,
  MedicinalProductPharmaceuticalCharacteristics,
  MedicinalProductPharmaceuticalRouteOfAdministration,
  MedicinalProductPharmaceuticalRouteOfAdministrationTargetSpecies,
  MedicinalProductPharmaceuticalRouteOfAdministrationTargetSpeciesWithdrawalPeriod,
  MedicinalProductUndesirableEffect,
  MessageDefinition,
  MessageDefinitionAllowedResponse,
  MessageDefinitionFocus,
  MessageHeader,
  MessageHeaderDestination,
  MessageHeaderResponse,
  MessageHeaderSource,
  MessageSignificanceCategory,
  MessageheaderResponseRequest,
  Meta,
  MimeType,
  MolecularSequence,
  MolecularSequenceQuality,
  MolecularSequenceQualityRoc,
  MolecularSequenceReferenceSeq,
  MolecularSequenceRepository,
  MolecularSequenceStructureVariant,
  MolecularSequenceStructureVariantInner,
  MolecularSequenceStructureVariantOuter,
  MolecularSequenceVariant,
  Money,
  MoneyQuantity,
  NameUse,
  NamingSystem,
  NamingSystemUniqueId,
  NamingSystemIdentifierType,
  NamingSystemType,
  Narrative,
  NarrativeStatus,
  NoteType,
  NutritiionOrderIntent,
  NutritionOrder,
  NutritionOrderEnteralFormula,
  NutritionOrderEnteralFormulaAdministration,
  NutritionOrderOralDiet,
  NutritionOrderOralDietNutrient,
  NutritionOrderOralDietTexture,
  NutritionOrderSupplement,
  NutritionOrderStatus,
  Observation,
  ObservationComponent,
  ObservationReferenceRange,
  ObservationDataType,
  ObservationDefinition,
  ObservationDefinitionQualifiedInterval,
  ObservationDefinitionQuantitativeDetails,
  ObservationRangeCategory,
  ObservationStatus,
  OperationDefinition,
  OperationDefinitionOverload,
  OperationDefinitionParameter,
  OperationDefinitionParameterBinding,
  OperationDefinitionParameterReferencedFrom,
  OperationKind,
  OperationOutcome,
  OperationOutcomeIssue,
  OperationParameterUse,
  Organization,
  OrganizationContact,
  OrganizationAffiliation,
  OrientationType,
  ParameterDefinition,
  ParameterUse,
  Parameters,
  ParametersParameter,
  ParticipantRequired,
  ParticipantStatus,
  ParticipationStatus,
  Patient,
  PatientCommunication,
  PatientContact,
  PatientLink,
  PaymentNotice,
  PaymentNoticeStatus,
  PaymentReconciliation,
  PaymentReconciliationDetail,
  PaymentReconciliationProcessNote,
  PaymentReconciliationStatus,
  Period,
  Person,
  PersonLink,
  PlanDefinition,
  PlanDefinitionAction,
  PlanDefinitionActionCondition,
  PlanDefinitionActionDynamicValue,
  PlanDefinitionActionParticipant,
  PlanDefinitionActionRelatedAction,
  PlanDefinitionGoal,
  PlanDefinitionGoalTarget,
  Population,
  Practitioner,
  PractitionerQualification,
  PractitionerRole,
  PractitionerRoleAvailableTime,
  PractitionerRoleNotAvailable,
  Procedure,
  ProcedureFocalDevice,
  ProcedurePerformer,
  ProcedureStatus,
  ProdCharacteristic,
  ProductShelfLife,
  PropertyRepresentation,
  PropertyType,
  Provenance,
  ProvenanceAgent,
  ProvenanceEntity,
  ProvenanceEntityRole,
  PublicationStatus,
  QualityType,
  Quantity,
  QuantityComparator,
  Questionnaire,
  QuestionnaireItem,
  QuestionnaireItemAnswerOption,
  QuestionnaireItemEnableWhen,
  QuestionnaireItemInitial,
  QuestionnaireItemOperator,
  QuestionnaireItemType,
  QuestionnaireResponse,
  QuestionnaireResponseItem,
  QuestionnaireResponseItemAnswer,
  QuestionnaireResponseStatus,
  Range,
  Ratio,
  Reference,
  ReferenceHandlingPolicy,
  ReferenceVersionRules,
  ReferredDocumentStatus,
  RelatedArtifact,
  RelatedArtifactType,
  RelatedPerson,
  RelatedPersonCommunication,
  RemittanceOutcome,
  RepositoryType,
  RequestGroup,
  RequestGroupAction,
  RequestGroupActionCondition,
  RequestGroupActionRelatedAction,
  RequestIntent,
  RequestPriority,
  RequestStatus,
  ResearchDefinition,
  ResearchElementDefinition,
  ResearchElementDefinitionCharacteristic,
  ResearchElementType,
  ResearchStudy,
  ResearchStudyArm,
  ResearchStudyObjective,
  ResearchStudyStatus,
  ResearchSubject,
  ResearchSubjectStatus,
  Resource,
  ResourceType,
  ResourceVersionPolicy,
  ResponseType,
  RestfulCapabilityMode,
  RiskAssessment,
  RiskAssessmentPrediction,
  RiskAssessmentStatus,
  RiskEvidenceSynthesis,
  RiskEvidenceSynthesisCertainty,
  RiskEvidenceSynthesisCertaintyCertaintySubcomponent,
  RiskEvidenceSynthesisRiskEstimate,
  RiskEvidenceSynthesisRiskEstimatePrecisionEstimate,
  RiskEvidenceSynthesisSampleSize,
  SPDXLicense,
  SampledData,
  Schedule,
  SearchComparator,
  SearchEntryMode,
  SearchModifierCode,
  SearchParamType,
  SearchParameter,
  SearchParameterComponent,
  SectionMode,
  SequenceType,
  ServiceRequest,
  ServiceRequestIntent,
  ServiceRequestPriority,
  ServiceRequestStatus,
  Signature,
  SimpleQuantity,
  SlicingRules,
  Slot,
  SlotStatus,
  SortDirection,
  Specimen,
  SpecimenCollection,
  SpecimenContainer,
  SpecimenProcessing,
  SpecimenContainedPreference,
  SpecimenDefinition,
  SpecimenDefinitionTypeTested,
  SpecimenDefinitionTypeTestedContainer,
  SpecimenDefinitionTypeTestedContainerAdditive,
  SpecimenDefinitionTypeTestedHandling,
  SpecimenStatus,
  Status,
  StrandType,
  StructureDefinition,
  StructureDefinitionContext,
  StructureDefinitionDifferential,
  StructureDefinitionMapping,
  StructureDefinitionSnapshot,
  StructureDefinitionKind,
  StructureMap,
  StructureMapGroup,
  StructureMapGroupInput,
  StructureMapGroupRule,
  StructureMapGroupRuleDependent,
  StructureMapGroupRuleSource,
  StructureMapGroupRuleTarget,
  StructureMapGroupRuleTargetParameter,
  StructureMapStructure,
  StructureMapContextType,
  StructureMapGroupTypeMode,
  StructureMapInputMode,
  StructureMapModelMode,
  StructureMapSourceListMode,
  StructureMapTargetListMode,
  StructureMapTransform,
  Subscription,
  SubscriptionChannel,
  SubscriptionChannelType,
  SubscriptionStatus,
  Substance,
  SubstanceIngredient,
  SubstanceInstance,
  SubstanceAmount,
  SubstanceAmountReferenceRange,
  SubstanceNucleicAcid,
  SubstanceNucleicAcidSubunit,
  SubstanceNucleicAcidSubunitLinkage,
  SubstanceNucleicAcidSubunitSugar,
  SubstancePolymer,
  SubstancePolymerMonomerSet,
  SubstancePolymerMonomerSetStartingMaterial,
  SubstancePolymerRepeat,
  SubstancePolymerRepeatRepeatUnit,
  SubstancePolymerRepeatRepeatUnitDegreeOfPolymerisation,
  SubstancePolymerRepeatRepeatUnitStructuralRepresentation,
  SubstanceProtein,
  SubstanceProteinSubunit,
  SubstanceReferenceInformation,
  SubstanceReferenceInformationClassification,
  SubstanceReferenceInformationGene,
  SubstanceReferenceInformationGeneElement,
  SubstanceReferenceInformationTarget,
  SubstanceSourceMaterial,
  SubstanceSourceMaterialFractionDescription,
  SubstanceSourceMaterialOrganism,
  SubstanceSourceMaterialOrganismAuthor,
  SubstanceSourceMaterialOrganismHybrid,
  SubstanceSourceMaterialOrganismOrganismGeneral,
  SubstanceSourceMaterialPartDescription,
  SubstanceSpecification,
  SubstanceSpecificationCode,
  SubstanceSpecificationMoiety,
  SubstanceSpecificationName,
  SubstanceSpecificationNameOfficial,
  SubstanceSpecificationProperty,
  SubstanceSpecificationRelationship,
  SubstanceSpecificationStructure,
  SubstanceSpecificationStructureIsotope,
  SubstanceSpecificationStructureIsotopeMolecularWeight,
  SubstanceSpecificationStructureRepresentation,
  SupplyDelivery,
  SupplyDeliverySuppliedItem,
  SupplyDeliveryStatus,
  SupplyRequest,
  SupplyRequestParameter,
  SupplyRequestStatus,
  SystemRestfulInteraction,
  Task,
  TaskInput,
  TaskOutput,
  TaskRestriction,
  TaskIntent,
  TaskPriority,
  TaskStatus,
  TerminologyCapabilities,
  TerminologyCapabilitiesClosure,
  TerminologyCapabilitiesCodeSystem,
  TerminologyCapabilitiesCodeSystemVersion,
  TerminologyCapabilitiesCodeSystemVersionFilter,
  TerminologyCapabilitiesExpansion,
  TerminologyCapabilitiesExpansionParameter,
  TerminologyCapabilitiesImplementation,
  TerminologyCapabilitiesSoftware,
  TerminologyCapabilitiesTranslation,
  TerminologyCapabilitiesValidateCode,
  TestReport,
  TestReportParticipant,
  TestReportSetup,
  TestReportSetupAction,
  TestReportSetupActionAssert,
  TestReportSetupActionOperation,
  TestReportTeardown,
  TestReportTeardownAction,
  TestReportTest,
  TestReportTestAction,
  TestReportActionResult,
  TestReportParticipantType,
  TestReportResult,
  TestReportStatus,
  TestScript,
  TestScriptDestination,
  TestScriptFixture,
  TestScriptMetadata,
  TestScriptMetadataCapability,
  TestScriptMetadataLink,
  TestScriptOrigin,
  TestScriptSetup,
  TestScriptSetupAction,
  TestScriptSetupActionAssert,
  TestScriptSetupActionOperation,
  TestScriptSetupActionOperationRequestHeader,
  TestScriptTeardown,
  TestScriptTeardownAction,
  TestScriptTest,
  TestScriptTestAction,
  TestScriptVariable,
  TestScriptRequestMethodCode,
  Timing,
  TimingRepeat,
  TriggerDefinition,
  TriggerType,
  TypeDerivationRule,
  TypeRestfulInteraction,
  UDIEntryType,
  UnitsOfTime,
  UsageContext,
  Use,
  ValueSet,
  ValueSetCompose,
  ValueSetComposeInclude,
  ValueSetComposeIncludeConcept,
  ValueSetComposeIncludeConceptDesignation,
  ValueSetComposeIncludeFilter,
  ValueSetExpansion,
  ValueSetExpansionContains,
  ValueSetExpansionParameter,
  VariableType,
  VerificationResult,
  VerificationResultAttestation,
  VerificationResultPrimarySource,
  VerificationResultValidator,
  VisionBase,
  VisionEyes,
  VisionPrescription,
  VisionPrescriptionLensSpecification,
  VisionPrescriptionLensSpecificationPrism,
  VisionStatus,
  XPathUsageType,
  PrimitiveBase64Binary,
  PrimitiveBoolean,
  PrimitiveCanonical,
  PrimitiveCode,
  PrimitiveDate,
  PrimitiveDateTime,
  PrimitiveDecimal,
  PrimitiveId,
  PrimitiveInstant,
  PrimitiveInteger,
  PrimitiveMarkdown,
  PrimitiveOid,
  PrimitivePositiveInt,
  PrimitiveQuestion,
  PrimitiveString,
  PrimitiveTime,
  PrimitiveUnsignedInt,
  PrimitiveUri,
  PrimitiveUrl,
  PrimitiveUuid,
  PrimitiveXhtml,
  Type,
} from "./internal";

const typeMapping: Record<string, typeof Type> = {
  "Account": Account,
  "AccountCoverage": AccountCoverage,
  "AccountGuarantor": AccountGuarantor,
  "AccountStatus": AccountStatus,
  "ActionCardinalityBehavior": ActionCardinalityBehavior,
  "ActionConditionKind": ActionConditionKind,
  "ActionGroupingBehavior": ActionGroupingBehavior,
  "ActionParticipantType": ActionParticipantType,
  "ActionPrecheckBehavior": ActionPrecheckBehavior,
  "ActionRelationshipType": ActionRelationshipType,
  "ActionRequiredBehavior": ActionRequiredBehavior,
  "ActionSelectionBehavior": ActionSelectionBehavior,
  "ActivityDefinition": ActivityDefinition,
  "ActivityDefinitionDynamicValue": ActivityDefinitionDynamicValue,
  "ActivityDefinitionParticipant": ActivityDefinitionParticipant,
  "ActivityDefinitionKind": ActivityDefinitionKind,
  "ActivityParticipantType": ActivityParticipantType,
  "Address": Address,
  "AddressType": AddressType,
  "AddressUse": AddressUse,
  "AdministrativeGender": AdministrativeGender,
  "AdverseEvent": AdverseEvent,
  "AdverseEventSuspectEntity": AdverseEventSuspectEntity,
  "AdverseEventSuspectEntityCausality": AdverseEventSuspectEntityCausality,
  "AdverseEventActuality": AdverseEventActuality,
  "Age": Age,
  "AggregationMode": AggregationMode,
  "AllergyIntolerance": AllergyIntolerance,
  "AllergyIntoleranceReaction": AllergyIntoleranceReaction,
  "AllergyIntoleranceCategory": AllergyIntoleranceCategory,
  "AllergyIntoleranceCriticality": AllergyIntoleranceCriticality,
  "AllergyIntoleranceSeverity": AllergyIntoleranceSeverity,
  "AllergyIntoleranceType": AllergyIntoleranceType,
  "Annotation": Annotation,
  "Appointment": Appointment,
  "AppointmentParticipant": AppointmentParticipant,
  "AppointmentResponse": AppointmentResponse,
  "AppointmentStatus": AppointmentStatus,
  "AssertionDirectionType": AssertionDirectionType,
  "AssertionOperatorType": AssertionOperatorType,
  "AssertionResponseTypes": AssertionResponseTypes,
  "Attachment": Attachment,
  "AuditEvent": AuditEvent,
  "AuditEventAgent": AuditEventAgent,
  "AuditEventAgentNetwork": AuditEventAgentNetwork,
  "AuditEventEntity": AuditEventEntity,
  "AuditEventEntityDetail": AuditEventEntityDetail,
  "AuditEventSource": AuditEventSource,
  "AuditEventAction": AuditEventAction,
  "AuditEventAgentNetworkType": AuditEventAgentNetworkType,
  "AuditEventOutcome": AuditEventOutcome,
  "BackboneElement": BackboneElement,
  "Basic": Basic,
  "Binary": Binary,
  "BindingStrength": BindingStrength,
  "BiologicallyDerivedProduct": BiologicallyDerivedProduct,
  "BiologicallyDerivedProductCollection": BiologicallyDerivedProductCollection,
  "BiologicallyDerivedProductManipulation": BiologicallyDerivedProductManipulation,
  "BiologicallyDerivedProductProcessing": BiologicallyDerivedProductProcessing,
  "BiologicallyDerivedProductStorage": BiologicallyDerivedProductStorage,
  "BiologicallyDerivedProductCategory": BiologicallyDerivedProductCategory,
  "BiologicallyDerivedProductStatus": BiologicallyDerivedProductStatus,
  "BiologicallyDerivedProductStorageScale": BiologicallyDerivedProductStorageScale,
  "BodyStructure": BodyStructure,
  "Bundle": Bundle,
  "BundleEntry": BundleEntry,
  "BundleEntryRequest": BundleEntryRequest,
  "BundleEntryResponse": BundleEntryResponse,
  "BundleEntrySearch": BundleEntrySearch,
  "BundleLink": BundleLink,
  "BundleType": BundleType,
  "CapabilityStatement": CapabilityStatement,
  "CapabilityStatementDocument": CapabilityStatementDocument,
  "CapabilityStatementImplementation": CapabilityStatementImplementation,
  "CapabilityStatementMessaging": CapabilityStatementMessaging,
  "CapabilityStatementMessagingEndpoint": CapabilityStatementMessagingEndpoint,
  "CapabilityStatementMessagingSupportedMessage": CapabilityStatementMessagingSupportedMessage,
  "CapabilityStatementRest": CapabilityStatementRest,
  "CapabilityStatementRestInteraction": CapabilityStatementRestInteraction,
  "CapabilityStatementRestResource": CapabilityStatementRestResource,
  "CapabilityStatementRestResourceInteraction": CapabilityStatementRestResourceInteraction,
  "CapabilityStatementRestResourceOperation": CapabilityStatementRestResourceOperation,
  "CapabilityStatementRestResourceSearchParam": CapabilityStatementRestResourceSearchParam,
  "CapabilityStatementRestSecurity": CapabilityStatementRestSecurity,
  "CapabilityStatementSoftware": CapabilityStatementSoftware,
  "CapabilityStatementKind": CapabilityStatementKind,
  "CarePlan": CarePlan,
  "CarePlanActivity": CarePlanActivity,
  "CarePlanActivityDetail": CarePlanActivityDetail,
  "CarePlanActivityKind": CarePlanActivityKind,
  "CarePlanActivityStatus": CarePlanActivityStatus,
  "CarePlanIntent": CarePlanIntent,
  "CarePlanStatus": CarePlanStatus,
  "CareTeam": CareTeam,
  "CareTeamParticipant": CareTeamParticipant,
  "CareTeamStatus": CareTeamStatus,
  "CatalogEntry": CatalogEntry,
  "CatalogEntryRelatedEntry": CatalogEntryRelatedEntry,
  "CatalogEntryRelationType": CatalogEntryRelationType,
  "ChargeItem": ChargeItem,
  "ChargeItemPerformer": ChargeItemPerformer,
  "ChargeItemDefinition": ChargeItemDefinition,
  "ChargeItemDefinitionApplicability": ChargeItemDefinitionApplicability,
  "ChargeItemDefinitionPropertyGroup": ChargeItemDefinitionPropertyGroup,
  "ChargeItemDefinitionPropertyGroupPriceComponent": ChargeItemDefinitionPropertyGroupPriceComponent,
  "ChargeItemDefinitionPriceComponentType": ChargeItemDefinitionPriceComponentType,
  "ChargeItemStatus": ChargeItemStatus,
  "Claim": Claim,
  "ClaimAccident": ClaimAccident,
  "ClaimCareTeam": ClaimCareTeam,
  "ClaimDiagnosis": ClaimDiagnosis,
  "ClaimInsurance": ClaimInsurance,
  "ClaimItem": ClaimItem,
  "ClaimItemDetail": ClaimItemDetail,
  "ClaimItemDetailSubDetail": ClaimItemDetailSubDetail,
  "ClaimPayee": ClaimPayee,
  "ClaimProcedure": ClaimProcedure,
  "ClaimRelated": ClaimRelated,
  "ClaimSupportingInfo": ClaimSupportingInfo,
  "ClaimResponse": ClaimResponse,
  "ClaimResponseAddItem": ClaimResponseAddItem,
  "ClaimResponseAddItemDetail": ClaimResponseAddItemDetail,
  "ClaimResponseAddItemDetailSubDetail": ClaimResponseAddItemDetailSubDetail,
  "ClaimResponseError": ClaimResponseError,
  "ClaimResponseInsurance": ClaimResponseInsurance,
  "ClaimResponseItem": ClaimResponseItem,
  "ClaimResponseItemAdjudication": ClaimResponseItemAdjudication,
  "ClaimResponseItemDetail": ClaimResponseItemDetail,
  "ClaimResponseItemDetailSubDetail": ClaimResponseItemDetailSubDetail,
  "ClaimResponsePayment": ClaimResponsePayment,
  "ClaimResponseProcessNote": ClaimResponseProcessNote,
  "ClaimResponseTotal": ClaimResponseTotal,
  "ClaimResponseStatus": ClaimResponseStatus,
  "ClaimStatus": ClaimStatus,
  "ClinicalImpression": ClinicalImpression,
  "ClinicalImpressionFinding": ClinicalImpressionFinding,
  "ClinicalImpressionInvestigation": ClinicalImpressionInvestigation,
  "ClinicalImpressionStatus": ClinicalImpressionStatus,
  "CodeSearchSupport": CodeSearchSupport,
  "CodeSystem": CodeSystem,
  "CodeSystemConcept": CodeSystemConcept,
  "CodeSystemConceptDesignation": CodeSystemConceptDesignation,
  "CodeSystemConceptProperty": CodeSystemConceptProperty,
  "CodeSystemFilter": CodeSystemFilter,
  "CodeSystemProperty": CodeSystemProperty,
  "CodeSystemContentMode": CodeSystemContentMode,
  "CodeSystemHierarchyMeaning": CodeSystemHierarchyMeaning,
  "CodeableConcept": CodeableConcept,
  "Coding": Coding,
  "Communication": Communication,
  "CommunicationPayload": CommunicationPayload,
  "CommunicationPriority": CommunicationPriority,
  "CommunicationRequest": CommunicationRequest,
  "CommunicationRequestPayload": CommunicationRequestPayload,
  "CommunicationRequestStatus": CommunicationRequestStatus,
  "CommunicationStatus": CommunicationStatus,
  "CompartmentCode": CompartmentCode,
  "CompartmentDefinition": CompartmentDefinition,
  "CompartmentDefinitionResource": CompartmentDefinitionResource,
  "CompartmentType": CompartmentType,
  "Composition": Composition,
  "CompositionAttester": CompositionAttester,
  "CompositionEvent": CompositionEvent,
  "CompositionRelatesTo": CompositionRelatesTo,
  "CompositionSection": CompositionSection,
  "CompositionAttestationMode": CompositionAttestationMode,
  "CompositionStatus": CompositionStatus,
  "ConceptMap": ConceptMap,
  "ConceptMapGroup": ConceptMapGroup,
  "ConceptMapGroupElement": ConceptMapGroupElement,
  "ConceptMapGroupElementTarget": ConceptMapGroupElementTarget,
  "ConceptMapGroupElementTargetDependsOn": ConceptMapGroupElementTargetDependsOn,
  "ConceptMapGroupUnmapped": ConceptMapGroupUnmapped,
  "ConceptMapEquivalence": ConceptMapEquivalence,
  "ConceptMapGroupUnmappedMode": ConceptMapGroupUnmappedMode,
  "Condition": Condition,
  "ConditionEvidence": ConditionEvidence,
  "ConditionStage": ConditionStage,
  "ConditionalDeleteStatus": ConditionalDeleteStatus,
  "ConditionalReadStatus": ConditionalReadStatus,
  "Consent": Consent,
  "ConsentPolicy": ConsentPolicy,
  "ConsentProvision": ConsentProvision,
  "ConsentProvisionActor": ConsentProvisionActor,
  "ConsentProvisionData": ConsentProvisionData,
  "ConsentVerification": ConsentVerification,
  "ConsentDataMeaning": ConsentDataMeaning,
  "ConsentProvisionType": ConsentProvisionType,
  "ConsentState": ConsentState,
  "ConstraintSeverity": ConstraintSeverity,
  "ContactDetail": ContactDetail,
  "ContactPoint": ContactPoint,
  "ContactPointSystem": ContactPointSystem,
  "ContactPointUse": ContactPointUse,
  "Contract": Contract,
  "ContractContentDefinition": ContractContentDefinition,
  "ContractFriendly": ContractFriendly,
  "ContractLegal": ContractLegal,
  "ContractRule": ContractRule,
  "ContractSigner": ContractSigner,
  "ContractTerm": ContractTerm,
  "ContractTermAction": ContractTermAction,
  "ContractTermActionSubject": ContractTermActionSubject,
  "ContractTermAsset": ContractTermAsset,
  "ContractTermAssetContext": ContractTermAssetContext,
  "ContractTermAssetValuedItem": ContractTermAssetValuedItem,
  "ContractTermOffer": ContractTermOffer,
  "ContractTermOfferAnswer": ContractTermOfferAnswer,
  "ContractTermOfferParty": ContractTermOfferParty,
  "ContractTermSecurityLabel": ContractTermSecurityLabel,
  "ContractPublicationStatus": ContractPublicationStatus,
  "ContractStatus": ContractStatus,
  "Contributor": Contributor,
  "ContributorType": ContributorType,
  "Count": Count,
  "Coverage": Coverage,
  "CoverageClass": CoverageClass,
  "CoverageCostToBeneficiary": CoverageCostToBeneficiary,
  "CoverageCostToBeneficiaryException": CoverageCostToBeneficiaryException,
  "CoverageEligibilityRequest": CoverageEligibilityRequest,
  "CoverageEligibilityRequestInsurance": CoverageEligibilityRequestInsurance,
  "CoverageEligibilityRequestItem": CoverageEligibilityRequestItem,
  "CoverageEligibilityRequestItemDiagnosis": CoverageEligibilityRequestItemDiagnosis,
  "CoverageEligibilityRequestSupportingInfo": CoverageEligibilityRequestSupportingInfo,
  "CoverageEligibilityResponse": CoverageEligibilityResponse,
  "CoverageEligibilityResponseError": CoverageEligibilityResponseError,
  "CoverageEligibilityResponseInsurance": CoverageEligibilityResponseInsurance,
  "CoverageEligibilityResponseInsuranceItem": CoverageEligibilityResponseInsuranceItem,
  "CoverageEligibilityResponseInsuranceItemBenefit": CoverageEligibilityResponseInsuranceItemBenefit,
  "CoverageStatus": CoverageStatus,
  "CurrencyCode": CurrencyCode,
  "DataRequirement": DataRequirement,
  "DataRequirementCodeFilter": DataRequirementCodeFilter,
  "DataRequirementDateFilter": DataRequirementDateFilter,
  "DataRequirementSort": DataRequirementSort,
  "DayOfWeek": DayOfWeek,
  "DaysOfWeek": DaysOfWeek,
  "DetectedIssue": DetectedIssue,
  "DetectedIssueEvidence": DetectedIssueEvidence,
  "DetectedIssueMitigation": DetectedIssueMitigation,
  "DetectedIssueSeverity": DetectedIssueSeverity,
  "DetectedIssueStatus": DetectedIssueStatus,
  "Device": Device,
  "DeviceDeviceName": DeviceDeviceName,
  "DeviceProperty": DeviceProperty,
  "DeviceSpecialization": DeviceSpecialization,
  "DeviceUdiCarrier": DeviceUdiCarrier,
  "DeviceVersion": DeviceVersion,
  "DeviceDefinition": DeviceDefinition,
  "DeviceDefinitionCapability": DeviceDefinitionCapability,
  "DeviceDefinitionDeviceName": DeviceDefinitionDeviceName,
  "DeviceDefinitionMaterial": DeviceDefinitionMaterial,
  "DeviceDefinitionProperty": DeviceDefinitionProperty,
  "DeviceDefinitionSpecialization": DeviceDefinitionSpecialization,
  "DeviceDefinitionUdiDeviceIdentifier": DeviceDefinitionUdiDeviceIdentifier,
  "DeviceMetric": DeviceMetric,
  "DeviceMetricCalibration": DeviceMetricCalibration,
  "DeviceMetricCalibrationState": DeviceMetricCalibrationState,
  "DeviceMetricCalibrationType": DeviceMetricCalibrationType,
  "DeviceMetricCategory": DeviceMetricCategory,
  "DeviceMetricColor": DeviceMetricColor,
  "DeviceMetricOperationalStatus": DeviceMetricOperationalStatus,
  "DeviceNameType": DeviceNameType,
  "DeviceRequest": DeviceRequest,
  "DeviceRequestParameter": DeviceRequestParameter,
  "DeviceRequestStatus": DeviceRequestStatus,
  "DeviceUseStatement": DeviceUseStatement,
  "DeviceUseStatementStatus": DeviceUseStatementStatus,
  "DiagnosticReport": DiagnosticReport,
  "DiagnosticReportMedia": DiagnosticReportMedia,
  "DiagnosticReportStatus": DiagnosticReportStatus,
  "DiscriminatorType": DiscriminatorType,
  "Distance": Distance,
  "DocumentConfidentiality": DocumentConfidentiality,
  "DocumentManifest": DocumentManifest,
  "DocumentManifestRelated": DocumentManifestRelated,
  "DocumentMode": DocumentMode,
  "DocumentReference": DocumentReference,
  "DocumentReferenceContent": DocumentReferenceContent,
  "DocumentReferenceContext": DocumentReferenceContext,
  "DocumentReferenceRelatesTo": DocumentReferenceRelatesTo,
  "DocumentReferenceStatus": DocumentReferenceStatus,
  "DocumentRelationshipType": DocumentRelationshipType,
  "DomainResource": DomainResource,
  "Dosage": Dosage,
  "DosageDoseAndRate": DosageDoseAndRate,
  "Duration": Duration,
  "EffectEvidenceSynthesis": EffectEvidenceSynthesis,
  "EffectEvidenceSynthesisCertainty": EffectEvidenceSynthesisCertainty,
  "EffectEvidenceSynthesisCertaintyCertaintySubcomponent": EffectEvidenceSynthesisCertaintyCertaintySubcomponent,
  "EffectEvidenceSynthesisEffectEstimate": EffectEvidenceSynthesisEffectEstimate,
  "EffectEvidenceSynthesisEffectEstimatePrecisionEstimate": EffectEvidenceSynthesisEffectEstimatePrecisionEstimate,
  "EffectEvidenceSynthesisResultsByExposure": EffectEvidenceSynthesisResultsByExposure,
  "EffectEvidenceSynthesisSampleSize": EffectEvidenceSynthesisSampleSize,
  "Element": Element,
  "ElementDefinition": ElementDefinition,
  "ElementDefinitionBase": ElementDefinitionBase,
  "ElementDefinitionBinding": ElementDefinitionBinding,
  "ElementDefinitionConstraint": ElementDefinitionConstraint,
  "ElementDefinitionExample": ElementDefinitionExample,
  "ElementDefinitionMapping": ElementDefinitionMapping,
  "ElementDefinitionSlicing": ElementDefinitionSlicing,
  "ElementDefinitionSlicingDiscriminator": ElementDefinitionSlicingDiscriminator,
  "ElementDefinitionType": ElementDefinitionType,
  "EligibilityRequestPurpose": EligibilityRequestPurpose,
  "EligibilityRequestStatus": EligibilityRequestStatus,
  "EligibilityResponsePurpose": EligibilityResponsePurpose,
  "EligibilityResponseStatus": EligibilityResponseStatus,
  "EnableWhenBehavior": EnableWhenBehavior,
  "Encounter": Encounter,
  "EncounterClassHistory": EncounterClassHistory,
  "EncounterDiagnosis": EncounterDiagnosis,
  "EncounterHospitalization": EncounterHospitalization,
  "EncounterLocation": EncounterLocation,
  "EncounterParticipant": EncounterParticipant,
  "EncounterStatusHistory": EncounterStatusHistory,
  "EncounterLocationStatus": EncounterLocationStatus,
  "EncounterStatus": EncounterStatus,
  "Endpoint": Endpoint,
  "EndpointStatus": EndpointStatus,
  "EnrollmentRequest": EnrollmentRequest,
  "EnrollmentRequestStatus": EnrollmentRequestStatus,
  "EnrollmentResponse": EnrollmentResponse,
  "EnrollmentResponseStatus": EnrollmentResponseStatus,
  "EpisodeOfCare": EpisodeOfCare,
  "EpisodeOfCareDiagnosis": EpisodeOfCareDiagnosis,
  "EpisodeOfCareStatusHistory": EpisodeOfCareStatusHistory,
  "EpisodeOfCareStatus": EpisodeOfCareStatus,
  "EventCapabilityMode": EventCapabilityMode,
  "EventDefinition": EventDefinition,
  "EventTiming": EventTiming,
  "Evidence": Evidence,
  "EvidenceVariable": EvidenceVariable,
  "EvidenceVariableCharacteristic": EvidenceVariableCharacteristic,
  "EvidenceVariableType": EvidenceVariableType,
  "ExampleScenario": ExampleScenario,
  "ExampleScenarioActor": ExampleScenarioActor,
  "ExampleScenarioInstance": ExampleScenarioInstance,
  "ExampleScenarioInstanceContainedInstance": ExampleScenarioInstanceContainedInstance,
  "ExampleScenarioInstanceVersion": ExampleScenarioInstanceVersion,
  "ExampleScenarioProcess": ExampleScenarioProcess,
  "ExampleScenarioProcessStep": ExampleScenarioProcessStep,
  "ExampleScenarioProcessStepAlternative": ExampleScenarioProcessStepAlternative,
  "ExampleScenarioProcessStepOperation": ExampleScenarioProcessStepOperation,
  "ExampleScenarioActorType": ExampleScenarioActorType,
  "ExplanationOfBenefit": ExplanationOfBenefit,
  "ExplanationOfBenefitAccident": ExplanationOfBenefitAccident,
  "ExplanationOfBenefitAddItem": ExplanationOfBenefitAddItem,
  "ExplanationOfBenefitAddItemDetail": ExplanationOfBenefitAddItemDetail,
  "ExplanationOfBenefitAddItemDetailSubDetail": ExplanationOfBenefitAddItemDetailSubDetail,
  "ExplanationOfBenefitBenefitBalance": ExplanationOfBenefitBenefitBalance,
  "ExplanationOfBenefitBenefitBalanceFinancial": ExplanationOfBenefitBenefitBalanceFinancial,
  "ExplanationOfBenefitCareTeam": ExplanationOfBenefitCareTeam,
  "ExplanationOfBenefitDiagnosis": ExplanationOfBenefitDiagnosis,
  "ExplanationOfBenefitInsurance": ExplanationOfBenefitInsurance,
  "ExplanationOfBenefitItem": ExplanationOfBenefitItem,
  "ExplanationOfBenefitItemAdjudication": ExplanationOfBenefitItemAdjudication,
  "ExplanationOfBenefitItemDetail": ExplanationOfBenefitItemDetail,
  "ExplanationOfBenefitItemDetailSubDetail": ExplanationOfBenefitItemDetailSubDetail,
  "ExplanationOfBenefitPayee": ExplanationOfBenefitPayee,
  "ExplanationOfBenefitPayment": ExplanationOfBenefitPayment,
  "ExplanationOfBenefitProcedure": ExplanationOfBenefitProcedure,
  "ExplanationOfBenefitProcessNote": ExplanationOfBenefitProcessNote,
  "ExplanationOfBenefitRelated": ExplanationOfBenefitRelated,
  "ExplanationOfBenefitSupportingInfo": ExplanationOfBenefitSupportingInfo,
  "ExplanationOfBenefitTotal": ExplanationOfBenefitTotal,
  "ExplanationOfBenefitStatus": ExplanationOfBenefitStatus,
  "ExposureState": ExposureState,
  "Expression": Expression,
  "Extension": Extension,
  "ExtensionContextType": ExtensionContextType,
  "FHIRAllTypes": FHIRAllTypes,
  "FHIRDefinedType": FHIRDefinedType,
  "FHIRDeviceStatus": FHIRDeviceStatus,
  "FHIRResourceType": FHIRResourceType,
  "FHIRSubstanceStatus": FHIRSubstanceStatus,
  "FHIRVersion": FHIRVersion,
  "FamilyHistoryStatus": FamilyHistoryStatus,
  "FamilyMemberHistory": FamilyMemberHistory,
  "FamilyMemberHistoryCondition": FamilyMemberHistoryCondition,
  "FilterOperator": FilterOperator,
  "Flag": Flag,
  "FlagStatus": FlagStatus,
  "Goal": Goal,
  "GoalTarget": GoalTarget,
  "GoalLifecycleStatus": GoalLifecycleStatus,
  "GraphCompartmentRule": GraphCompartmentRule,
  "GraphCompartmentUse": GraphCompartmentUse,
  "GraphDefinition": GraphDefinition,
  "GraphDefinitionLink": GraphDefinitionLink,
  "GraphDefinitionLinkTarget": GraphDefinitionLinkTarget,
  "GraphDefinitionLinkTargetCompartment": GraphDefinitionLinkTargetCompartment,
  "Group": Group,
  "GroupCharacteristic": GroupCharacteristic,
  "GroupMember": GroupMember,
  "GroupMeasure": GroupMeasure,
  "GroupType": GroupType,
  "GuidanceResponse": GuidanceResponse,
  "GuidanceResponseStatus": GuidanceResponseStatus,
  "GuidePageGeneration": GuidePageGeneration,
  "GuideParameterCode": GuideParameterCode,
  "HTTPVerb": HTTPVerb,
  "HealthcareService": HealthcareService,
  "HealthcareServiceAvailableTime": HealthcareServiceAvailableTime,
  "HealthcareServiceEligibility": HealthcareServiceEligibility,
  "HealthcareServiceNotAvailable": HealthcareServiceNotAvailable,
  "HumanName": HumanName,
  "Identifier": Identifier,
  "IdentifierUse": IdentifierUse,
  "IdentityAssuranceLevel": IdentityAssuranceLevel,
  "ImagingStudy": ImagingStudy,
  "ImagingStudySeries": ImagingStudySeries,
  "ImagingStudySeriesInstance": ImagingStudySeriesInstance,
  "ImagingStudySeriesPerformer": ImagingStudySeriesPerformer,
  "ImagingStudyStatus": ImagingStudyStatus,
  "Immunization": Immunization,
  "ImmunizationEducation": ImmunizationEducation,
  "ImmunizationPerformer": ImmunizationPerformer,
  "ImmunizationProtocolApplied": ImmunizationProtocolApplied,
  "ImmunizationReaction": ImmunizationReaction,
  "ImmunizationEvaluation": ImmunizationEvaluation,
  "ImmunizationEvaluationStatus": ImmunizationEvaluationStatus,
  "ImmunizationRecommendation": ImmunizationRecommendation,
  "ImmunizationRecommendationRecommendation": ImmunizationRecommendationRecommendation,
  "ImmunizationRecommendationRecommendationDateCriterion": ImmunizationRecommendationRecommendationDateCriterion,
  "ImmunizationStatus": ImmunizationStatus,
  "ImplementationGuide": ImplementationGuide,
  "ImplementationGuideDefinition": ImplementationGuideDefinition,
  "ImplementationGuideDefinitionGrouping": ImplementationGuideDefinitionGrouping,
  "ImplementationGuideDefinitionPage": ImplementationGuideDefinitionPage,
  "ImplementationGuideDefinitionParameter": ImplementationGuideDefinitionParameter,
  "ImplementationGuideDefinitionResource": ImplementationGuideDefinitionResource,
  "ImplementationGuideDefinitionTemplate": ImplementationGuideDefinitionTemplate,
  "ImplementationGuideDependsOn": ImplementationGuideDependsOn,
  "ImplementationGuideGlobal": ImplementationGuideGlobal,
  "ImplementationGuideManifest": ImplementationGuideManifest,
  "ImplementationGuideManifestPage": ImplementationGuideManifestPage,
  "ImplementationGuideManifestResource": ImplementationGuideManifestResource,
  "InsurancePlan": InsurancePlan,
  "InsurancePlanContact": InsurancePlanContact,
  "InsurancePlanCoverage": InsurancePlanCoverage,
  "InsurancePlanCoverageBenefit": InsurancePlanCoverageBenefit,
  "InsurancePlanCoverageBenefitLimit": InsurancePlanCoverageBenefitLimit,
  "InsurancePlanPlan": InsurancePlanPlan,
  "InsurancePlanPlanGeneralCost": InsurancePlanPlanGeneralCost,
  "InsurancePlanPlanSpecificCost": InsurancePlanPlanSpecificCost,
  "InsurancePlanPlanSpecificCostBenefit": InsurancePlanPlanSpecificCostBenefit,
  "InsurancePlanPlanSpecificCostBenefitCost": InsurancePlanPlanSpecificCostBenefitCost,
  "Invoice": Invoice,
  "InvoiceLineItem": InvoiceLineItem,
  "InvoiceLineItemPriceComponent": InvoiceLineItemPriceComponent,
  "InvoiceParticipant": InvoiceParticipant,
  "InvoicePriceComponentType": InvoicePriceComponentType,
  "InvoiceStatus": InvoiceStatus,
  "IssueSeverity": IssueSeverity,
  "IssueType": IssueType,
  "Library": Library,
  "LinkType": LinkType,
  "Linkage": Linkage,
  "LinkageItem": LinkageItem,
  "LinkageType": LinkageType,
  "List": List,
  "ListEntry": ListEntry,
  "ListMode": ListMode,
  "ListStatus": ListStatus,
  "Location": Location,
  "LocationHoursOfOperation": LocationHoursOfOperation,
  "LocationPosition": LocationPosition,
  "LocationMode": LocationMode,
  "LocationStatus": LocationStatus,
  "MarketingStatus": MarketingStatus,
  "Measure": Measure,
  "MeasureGroup": MeasureGroup,
  "MeasureGroupPopulation": MeasureGroupPopulation,
  "MeasureGroupStratifier": MeasureGroupStratifier,
  "MeasureGroupStratifierComponent": MeasureGroupStratifierComponent,
  "MeasureSupplementalData": MeasureSupplementalData,
  "MeasureReport": MeasureReport,
  "MeasureReportGroup": MeasureReportGroup,
  "MeasureReportGroupPopulation": MeasureReportGroupPopulation,
  "MeasureReportGroupStratifier": MeasureReportGroupStratifier,
  "MeasureReportGroupStratifierStratum": MeasureReportGroupStratifierStratum,
  "MeasureReportGroupStratifierStratumComponent": MeasureReportGroupStratifierStratumComponent,
  "MeasureReportGroupStratifierStratumPopulation": MeasureReportGroupStratifierStratumPopulation,
  "MeasureReportStatus": MeasureReportStatus,
  "MeasureReportType": MeasureReportType,
  "Media": Media,
  "MediaStatus": MediaStatus,
  "Medication": Medication,
  "MedicationBatch": MedicationBatch,
  "MedicationIngredient": MedicationIngredient,
  "MedicationAdministration": MedicationAdministration,
  "MedicationAdministrationDosage": MedicationAdministrationDosage,
  "MedicationAdministrationPerformer": MedicationAdministrationPerformer,
  "MedicationAdministrationStatus": MedicationAdministrationStatus,
  "MedicationDispense": MedicationDispense,
  "MedicationDispensePerformer": MedicationDispensePerformer,
  "MedicationDispenseSubstitution": MedicationDispenseSubstitution,
  "MedicationDispenseStatus": MedicationDispenseStatus,
  "MedicationKnowledge": MedicationKnowledge,
  "MedicationKnowledgeAdministrationGuidelines": MedicationKnowledgeAdministrationGuidelines,
  "MedicationKnowledgeAdministrationGuidelinesDosage": MedicationKnowledgeAdministrationGuidelinesDosage,
  "MedicationKnowledgeAdministrationGuidelinesPatientCharacteristics": MedicationKnowledgeAdministrationGuidelinesPatientCharacteristics,
  "MedicationKnowledgeCost": MedicationKnowledgeCost,
  "MedicationKnowledgeDrugCharacteristic": MedicationKnowledgeDrugCharacteristic,
  "MedicationKnowledgeIngredient": MedicationKnowledgeIngredient,
  "MedicationKnowledgeKinetics": MedicationKnowledgeKinetics,
  "MedicationKnowledgeMedicineClassification": MedicationKnowledgeMedicineClassification,
  "MedicationKnowledgeMonitoringProgram": MedicationKnowledgeMonitoringProgram,
  "MedicationKnowledgeMonograph": MedicationKnowledgeMonograph,
  "MedicationKnowledgePackaging": MedicationKnowledgePackaging,
  "MedicationKnowledgeRegulatory": MedicationKnowledgeRegulatory,
  "MedicationKnowledgeRegulatoryMaxDispense": MedicationKnowledgeRegulatoryMaxDispense,
  "MedicationKnowledgeRegulatorySchedule": MedicationKnowledgeRegulatorySchedule,
  "MedicationKnowledgeRegulatorySubstitution": MedicationKnowledgeRegulatorySubstitution,
  "MedicationKnowledgeRelatedMedicationKnowledge": MedicationKnowledgeRelatedMedicationKnowledge,
  "MedicationKnowledgeStatus": MedicationKnowledgeStatus,
  "MedicationRequest": MedicationRequest,
  "MedicationRequestDispenseRequest": MedicationRequestDispenseRequest,
  "MedicationRequestDispenseRequestInitialFill": MedicationRequestDispenseRequestInitialFill,
  "MedicationRequestSubstitution": MedicationRequestSubstitution,
  "MedicationRequestIntent": MedicationRequestIntent,
  "MedicationRequestPriority": MedicationRequestPriority,
  "MedicationRequestStatus": MedicationRequestStatus,
  "MedicationStatement": MedicationStatement,
  "MedicationStatementStatus": MedicationStatementStatus,
  "MedicationStatus": MedicationStatus,
  "MedicinalProduct": MedicinalProduct,
  "MedicinalProductManufacturingBusinessOperation": MedicinalProductManufacturingBusinessOperation,
  "MedicinalProductName": MedicinalProductName,
  "MedicinalProductNameCountryLanguage": MedicinalProductNameCountryLanguage,
  "MedicinalProductNameNamePart": MedicinalProductNameNamePart,
  "MedicinalProductSpecialDesignation": MedicinalProductSpecialDesignation,
  "MedicinalProductAuthorization": MedicinalProductAuthorization,
  "MedicinalProductAuthorizationJurisdictionalAuthorization": MedicinalProductAuthorizationJurisdictionalAuthorization,
  "MedicinalProductAuthorizationProcedure": MedicinalProductAuthorizationProcedure,
  "MedicinalProductContraindication": MedicinalProductContraindication,
  "MedicinalProductContraindicationOtherTherapy": MedicinalProductContraindicationOtherTherapy,
  "MedicinalProductIndication": MedicinalProductIndication,
  "MedicinalProductIndicationOtherTherapy": MedicinalProductIndicationOtherTherapy,
  "MedicinalProductIngredient": MedicinalProductIngredient,
  "MedicinalProductIngredientSpecifiedSubstance": MedicinalProductIngredientSpecifiedSubstance,
  "MedicinalProductIngredientSpecifiedSubstanceStrength": MedicinalProductIngredientSpecifiedSubstanceStrength,
  "MedicinalProductIngredientSpecifiedSubstanceStrengthReferenceStrength": MedicinalProductIngredientSpecifiedSubstanceStrengthReferenceStrength,
  "MedicinalProductIngredientSubstance": MedicinalProductIngredientSubstance,
  "MedicinalProductInteraction": MedicinalProductInteraction,
  "MedicinalProductInteractionInteractant": MedicinalProductInteractionInteractant,
  "MedicinalProductManufactured": MedicinalProductManufactured,
  "MedicinalProductPackaged": MedicinalProductPackaged,
  "MedicinalProductPackagedBatchIdentifier": MedicinalProductPackagedBatchIdentifier,
  "MedicinalProductPackagedPackageItem": MedicinalProductPackagedPackageItem,
  "MedicinalProductPharmaceutical": MedicinalProductPharmaceutical,
  "MedicinalProductPharmaceuticalCharacteristics": MedicinalProductPharmaceuticalCharacteristics,
  "MedicinalProductPharmaceuticalRouteOfAdministration": MedicinalProductPharmaceuticalRouteOfAdministration,
  "MedicinalProductPharmaceuticalRouteOfAdministrationTargetSpecies": MedicinalProductPharmaceuticalRouteOfAdministrationTargetSpecies,
  "MedicinalProductPharmaceuticalRouteOfAdministrationTargetSpeciesWithdrawalPeriod": MedicinalProductPharmaceuticalRouteOfAdministrationTargetSpeciesWithdrawalPeriod,
  "MedicinalProductUndesirableEffect": MedicinalProductUndesirableEffect,
  "MessageDefinition": MessageDefinition,
  "MessageDefinitionAllowedResponse": MessageDefinitionAllowedResponse,
  "MessageDefinitionFocus": MessageDefinitionFocus,
  "MessageHeader": MessageHeader,
  "MessageHeaderDestination": MessageHeaderDestination,
  "MessageHeaderResponse": MessageHeaderResponse,
  "MessageHeaderSource": MessageHeaderSource,
  "MessageSignificanceCategory": MessageSignificanceCategory,
  "MessageheaderResponseRequest": MessageheaderResponseRequest,
  "Meta": Meta,
  "MimeType": MimeType,
  "MolecularSequence": MolecularSequence,
  "MolecularSequenceQuality": MolecularSequenceQuality,
  "MolecularSequenceQualityRoc": MolecularSequenceQualityRoc,
  "MolecularSequenceReferenceSeq": MolecularSequenceReferenceSeq,
  "MolecularSequenceRepository": MolecularSequenceRepository,
  "MolecularSequenceStructureVariant": MolecularSequenceStructureVariant,
  "MolecularSequenceStructureVariantInner": MolecularSequenceStructureVariantInner,
  "MolecularSequenceStructureVariantOuter": MolecularSequenceStructureVariantOuter,
  "MolecularSequenceVariant": MolecularSequenceVariant,
  "Money": Money,
  "MoneyQuantity": MoneyQuantity,
  "NameUse": NameUse,
  "NamingSystem": NamingSystem,
  "NamingSystemUniqueId": NamingSystemUniqueId,
  "NamingSystemIdentifierType": NamingSystemIdentifierType,
  "NamingSystemType": NamingSystemType,
  "Narrative": Narrative,
  "NarrativeStatus": NarrativeStatus,
  "NoteType": NoteType,
  "NutritiionOrderIntent": NutritiionOrderIntent,
  "NutritionOrder": NutritionOrder,
  "NutritionOrderEnteralFormula": NutritionOrderEnteralFormula,
  "NutritionOrderEnteralFormulaAdministration": NutritionOrderEnteralFormulaAdministration,
  "NutritionOrderOralDiet": NutritionOrderOralDiet,
  "NutritionOrderOralDietNutrient": NutritionOrderOralDietNutrient,
  "NutritionOrderOralDietTexture": NutritionOrderOralDietTexture,
  "NutritionOrderSupplement": NutritionOrderSupplement,
  "NutritionOrderStatus": NutritionOrderStatus,
  "Observation": Observation,
  "ObservationComponent": ObservationComponent,
  "ObservationReferenceRange": ObservationReferenceRange,
  "ObservationDataType": ObservationDataType,
  "ObservationDefinition": ObservationDefinition,
  "ObservationDefinitionQualifiedInterval": ObservationDefinitionQualifiedInterval,
  "ObservationDefinitionQuantitativeDetails": ObservationDefinitionQuantitativeDetails,
  "ObservationRangeCategory": ObservationRangeCategory,
  "ObservationStatus": ObservationStatus,
  "OperationDefinition": OperationDefinition,
  "OperationDefinitionOverload": OperationDefinitionOverload,
  "OperationDefinitionParameter": OperationDefinitionParameter,
  "OperationDefinitionParameterBinding": OperationDefinitionParameterBinding,
  "OperationDefinitionParameterReferencedFrom": OperationDefinitionParameterReferencedFrom,
  "OperationKind": OperationKind,
  "OperationOutcome": OperationOutcome,
  "OperationOutcomeIssue": OperationOutcomeIssue,
  "OperationParameterUse": OperationParameterUse,
  "Organization": Organization,
  "OrganizationContact": OrganizationContact,
  "OrganizationAffiliation": OrganizationAffiliation,
  "OrientationType": OrientationType,
  "ParameterDefinition": ParameterDefinition,
  "ParameterUse": ParameterUse,
  "Parameters": Parameters,
  "ParametersParameter": ParametersParameter,
  "ParticipantRequired": ParticipantRequired,
  "ParticipantStatus": ParticipantStatus,
  "ParticipationStatus": ParticipationStatus,
  "Patient": Patient,
  "PatientCommunication": PatientCommunication,
  "PatientContact": PatientContact,
  "PatientLink": PatientLink,
  "PaymentNotice": PaymentNotice,
  "PaymentNoticeStatus": PaymentNoticeStatus,
  "PaymentReconciliation": PaymentReconciliation,
  "PaymentReconciliationDetail": PaymentReconciliationDetail,
  "PaymentReconciliationProcessNote": PaymentReconciliationProcessNote,
  "PaymentReconciliationStatus": PaymentReconciliationStatus,
  "Period": Period,
  "Person": Person,
  "PersonLink": PersonLink,
  "PlanDefinition": PlanDefinition,
  "PlanDefinitionAction": PlanDefinitionAction,
  "PlanDefinitionActionCondition": PlanDefinitionActionCondition,
  "PlanDefinitionActionDynamicValue": PlanDefinitionActionDynamicValue,
  "PlanDefinitionActionParticipant": PlanDefinitionActionParticipant,
  "PlanDefinitionActionRelatedAction": PlanDefinitionActionRelatedAction,
  "PlanDefinitionGoal": PlanDefinitionGoal,
  "PlanDefinitionGoalTarget": PlanDefinitionGoalTarget,
  "Population": Population,
  "Practitioner": Practitioner,
  "PractitionerQualification": PractitionerQualification,
  "PractitionerRole": PractitionerRole,
  "PractitionerRoleAvailableTime": PractitionerRoleAvailableTime,
  "PractitionerRoleNotAvailable": PractitionerRoleNotAvailable,
  "Procedure": Procedure,
  "ProcedureFocalDevice": ProcedureFocalDevice,
  "ProcedurePerformer": ProcedurePerformer,
  "ProcedureStatus": ProcedureStatus,
  "ProdCharacteristic": ProdCharacteristic,
  "ProductShelfLife": ProductShelfLife,
  "PropertyRepresentation": PropertyRepresentation,
  "PropertyType": PropertyType,
  "Provenance": Provenance,
  "ProvenanceAgent": ProvenanceAgent,
  "ProvenanceEntity": ProvenanceEntity,
  "ProvenanceEntityRole": ProvenanceEntityRole,
  "PublicationStatus": PublicationStatus,
  "QualityType": QualityType,
  "Quantity": Quantity,
  "QuantityComparator": QuantityComparator,
  "Questionnaire": Questionnaire,
  "QuestionnaireItem": QuestionnaireItem,
  "QuestionnaireItemAnswerOption": QuestionnaireItemAnswerOption,
  "QuestionnaireItemEnableWhen": QuestionnaireItemEnableWhen,
  "QuestionnaireItemInitial": QuestionnaireItemInitial,
  "QuestionnaireItemOperator": QuestionnaireItemOperator,
  "QuestionnaireItemType": QuestionnaireItemType,
  "QuestionnaireResponse": QuestionnaireResponse,
  "QuestionnaireResponseItem": QuestionnaireResponseItem,
  "QuestionnaireResponseItemAnswer": QuestionnaireResponseItemAnswer,
  "QuestionnaireResponseStatus": QuestionnaireResponseStatus,
  "Range": Range,
  "Ratio": Ratio,
  "Reference": Reference,
  "ReferenceHandlingPolicy": ReferenceHandlingPolicy,
  "ReferenceVersionRules": ReferenceVersionRules,
  "ReferredDocumentStatus": ReferredDocumentStatus,
  "RelatedArtifact": RelatedArtifact,
  "RelatedArtifactType": RelatedArtifactType,
  "RelatedPerson": RelatedPerson,
  "RelatedPersonCommunication": RelatedPersonCommunication,
  "RemittanceOutcome": RemittanceOutcome,
  "RepositoryType": RepositoryType,
  "RequestGroup": RequestGroup,
  "RequestGroupAction": RequestGroupAction,
  "RequestGroupActionCondition": RequestGroupActionCondition,
  "RequestGroupActionRelatedAction": RequestGroupActionRelatedAction,
  "RequestIntent": RequestIntent,
  "RequestPriority": RequestPriority,
  "RequestStatus": RequestStatus,
  "ResearchDefinition": ResearchDefinition,
  "ResearchElementDefinition": ResearchElementDefinition,
  "ResearchElementDefinitionCharacteristic": ResearchElementDefinitionCharacteristic,
  "ResearchElementType": ResearchElementType,
  "ResearchStudy": ResearchStudy,
  "ResearchStudyArm": ResearchStudyArm,
  "ResearchStudyObjective": ResearchStudyObjective,
  "ResearchStudyStatus": ResearchStudyStatus,
  "ResearchSubject": ResearchSubject,
  "ResearchSubjectStatus": ResearchSubjectStatus,
  "Resource": Resource,
  "ResourceType": ResourceType,
  "ResourceVersionPolicy": ResourceVersionPolicy,
  "ResponseType": ResponseType,
  "RestfulCapabilityMode": RestfulCapabilityMode,
  "RiskAssessment": RiskAssessment,
  "RiskAssessmentPrediction": RiskAssessmentPrediction,
  "RiskAssessmentStatus": RiskAssessmentStatus,
  "RiskEvidenceSynthesis": RiskEvidenceSynthesis,
  "RiskEvidenceSynthesisCertainty": RiskEvidenceSynthesisCertainty,
  "RiskEvidenceSynthesisCertaintyCertaintySubcomponent": RiskEvidenceSynthesisCertaintyCertaintySubcomponent,
  "RiskEvidenceSynthesisRiskEstimate": RiskEvidenceSynthesisRiskEstimate,
  "RiskEvidenceSynthesisRiskEstimatePrecisionEstimate": RiskEvidenceSynthesisRiskEstimatePrecisionEstimate,
  "RiskEvidenceSynthesisSampleSize": RiskEvidenceSynthesisSampleSize,
  "SPDXLicense": SPDXLicense,
  "SampledData": SampledData,
  "Schedule": Schedule,
  "SearchComparator": SearchComparator,
  "SearchEntryMode": SearchEntryMode,
  "SearchModifierCode": SearchModifierCode,
  "SearchParamType": SearchParamType,
  "SearchParameter": SearchParameter,
  "SearchParameterComponent": SearchParameterComponent,
  "SectionMode": SectionMode,
  "SequenceType": SequenceType,
  "ServiceRequest": ServiceRequest,
  "ServiceRequestIntent": ServiceRequestIntent,
  "ServiceRequestPriority": ServiceRequestPriority,
  "ServiceRequestStatus": ServiceRequestStatus,
  "Signature": Signature,
  "SimpleQuantity": SimpleQuantity,
  "SlicingRules": SlicingRules,
  "Slot": Slot,
  "SlotStatus": SlotStatus,
  "SortDirection": SortDirection,
  "Specimen": Specimen,
  "SpecimenCollection": SpecimenCollection,
  "SpecimenContainer": SpecimenContainer,
  "SpecimenProcessing": SpecimenProcessing,
  "SpecimenContainedPreference": SpecimenContainedPreference,
  "SpecimenDefinition": SpecimenDefinition,
  "SpecimenDefinitionTypeTested": SpecimenDefinitionTypeTested,
  "SpecimenDefinitionTypeTestedContainer": SpecimenDefinitionTypeTestedContainer,
  "SpecimenDefinitionTypeTestedContainerAdditive": SpecimenDefinitionTypeTestedContainerAdditive,
  "SpecimenDefinitionTypeTestedHandling": SpecimenDefinitionTypeTestedHandling,
  "SpecimenStatus": SpecimenStatus,
  "Status": Status,
  "StrandType": StrandType,
  "StructureDefinition": StructureDefinition,
  "StructureDefinitionContext": StructureDefinitionContext,
  "StructureDefinitionDifferential": StructureDefinitionDifferential,
  "StructureDefinitionMapping": StructureDefinitionMapping,
  "StructureDefinitionSnapshot": StructureDefinitionSnapshot,
  "StructureDefinitionKind": StructureDefinitionKind,
  "StructureMap": StructureMap,
  "StructureMapGroup": StructureMapGroup,
  "StructureMapGroupInput": StructureMapGroupInput,
  "StructureMapGroupRule": StructureMapGroupRule,
  "StructureMapGroupRuleDependent": StructureMapGroupRuleDependent,
  "StructureMapGroupRuleSource": StructureMapGroupRuleSource,
  "StructureMapGroupRuleTarget": StructureMapGroupRuleTarget,
  "StructureMapGroupRuleTargetParameter": StructureMapGroupRuleTargetParameter,
  "StructureMapStructure": StructureMapStructure,
  "StructureMapContextType": StructureMapContextType,
  "StructureMapGroupTypeMode": StructureMapGroupTypeMode,
  "StructureMapInputMode": StructureMapInputMode,
  "StructureMapModelMode": StructureMapModelMode,
  "StructureMapSourceListMode": StructureMapSourceListMode,
  "StructureMapTargetListMode": StructureMapTargetListMode,
  "StructureMapTransform": StructureMapTransform,
  "Subscription": Subscription,
  "SubscriptionChannel": SubscriptionChannel,
  "SubscriptionChannelType": SubscriptionChannelType,
  "SubscriptionStatus": SubscriptionStatus,
  "Substance": Substance,
  "SubstanceIngredient": SubstanceIngredient,
  "SubstanceInstance": SubstanceInstance,
  "SubstanceAmount": SubstanceAmount,
  "SubstanceAmountReferenceRange": SubstanceAmountReferenceRange,
  "SubstanceNucleicAcid": SubstanceNucleicAcid,
  "SubstanceNucleicAcidSubunit": SubstanceNucleicAcidSubunit,
  "SubstanceNucleicAcidSubunitLinkage": SubstanceNucleicAcidSubunitLinkage,
  "SubstanceNucleicAcidSubunitSugar": SubstanceNucleicAcidSubunitSugar,
  "SubstancePolymer": SubstancePolymer,
  "SubstancePolymerMonomerSet": SubstancePolymerMonomerSet,
  "SubstancePolymerMonomerSetStartingMaterial": SubstancePolymerMonomerSetStartingMaterial,
  "SubstancePolymerRepeat": SubstancePolymerRepeat,
  "SubstancePolymerRepeatRepeatUnit": SubstancePolymerRepeatRepeatUnit,
  "SubstancePolymerRepeatRepeatUnitDegreeOfPolymerisation": SubstancePolymerRepeatRepeatUnitDegreeOfPolymerisation,
  "SubstancePolymerRepeatRepeatUnitStructuralRepresentation": SubstancePolymerRepeatRepeatUnitStructuralRepresentation,
  "SubstanceProtein": SubstanceProtein,
  "SubstanceProteinSubunit": SubstanceProteinSubunit,
  "SubstanceReferenceInformation": SubstanceReferenceInformation,
  "SubstanceReferenceInformationClassification": SubstanceReferenceInformationClassification,
  "SubstanceReferenceInformationGene": SubstanceReferenceInformationGene,
  "SubstanceReferenceInformationGeneElement": SubstanceReferenceInformationGeneElement,
  "SubstanceReferenceInformationTarget": SubstanceReferenceInformationTarget,
  "SubstanceSourceMaterial": SubstanceSourceMaterial,
  "SubstanceSourceMaterialFractionDescription": SubstanceSourceMaterialFractionDescription,
  "SubstanceSourceMaterialOrganism": SubstanceSourceMaterialOrganism,
  "SubstanceSourceMaterialOrganismAuthor": SubstanceSourceMaterialOrganismAuthor,
  "SubstanceSourceMaterialOrganismHybrid": SubstanceSourceMaterialOrganismHybrid,
  "SubstanceSourceMaterialOrganismOrganismGeneral": SubstanceSourceMaterialOrganismOrganismGeneral,
  "SubstanceSourceMaterialPartDescription": SubstanceSourceMaterialPartDescription,
  "SubstanceSpecification": SubstanceSpecification,
  "SubstanceSpecificationCode": SubstanceSpecificationCode,
  "SubstanceSpecificationMoiety": SubstanceSpecificationMoiety,
  "SubstanceSpecificationName": SubstanceSpecificationName,
  "SubstanceSpecificationNameOfficial": SubstanceSpecificationNameOfficial,
  "SubstanceSpecificationProperty": SubstanceSpecificationProperty,
  "SubstanceSpecificationRelationship": SubstanceSpecificationRelationship,
  "SubstanceSpecificationStructure": SubstanceSpecificationStructure,
  "SubstanceSpecificationStructureIsotope": SubstanceSpecificationStructureIsotope,
  "SubstanceSpecificationStructureIsotopeMolecularWeight": SubstanceSpecificationStructureIsotopeMolecularWeight,
  "SubstanceSpecificationStructureRepresentation": SubstanceSpecificationStructureRepresentation,
  "SupplyDelivery": SupplyDelivery,
  "SupplyDeliverySuppliedItem": SupplyDeliverySuppliedItem,
  "SupplyDeliveryStatus": SupplyDeliveryStatus,
  "SupplyRequest": SupplyRequest,
  "SupplyRequestParameter": SupplyRequestParameter,
  "SupplyRequestStatus": SupplyRequestStatus,
  "SystemRestfulInteraction": SystemRestfulInteraction,
  "Task": Task,
  "TaskInput": TaskInput,
  "TaskOutput": TaskOutput,
  "TaskRestriction": TaskRestriction,
  "TaskIntent": TaskIntent,
  "TaskPriority": TaskPriority,
  "TaskStatus": TaskStatus,
  "TerminologyCapabilities": TerminologyCapabilities,
  "TerminologyCapabilitiesClosure": TerminologyCapabilitiesClosure,
  "TerminologyCapabilitiesCodeSystem": TerminologyCapabilitiesCodeSystem,
  "TerminologyCapabilitiesCodeSystemVersion": TerminologyCapabilitiesCodeSystemVersion,
  "TerminologyCapabilitiesCodeSystemVersionFilter": TerminologyCapabilitiesCodeSystemVersionFilter,
  "TerminologyCapabilitiesExpansion": TerminologyCapabilitiesExpansion,
  "TerminologyCapabilitiesExpansionParameter": TerminologyCapabilitiesExpansionParameter,
  "TerminologyCapabilitiesImplementation": TerminologyCapabilitiesImplementation,
  "TerminologyCapabilitiesSoftware": TerminologyCapabilitiesSoftware,
  "TerminologyCapabilitiesTranslation": TerminologyCapabilitiesTranslation,
  "TerminologyCapabilitiesValidateCode": TerminologyCapabilitiesValidateCode,
  "TestReport": TestReport,
  "TestReportParticipant": TestReportParticipant,
  "TestReportSetup": TestReportSetup,
  "TestReportSetupAction": TestReportSetupAction,
  "TestReportSetupActionAssert": TestReportSetupActionAssert,
  "TestReportSetupActionOperation": TestReportSetupActionOperation,
  "TestReportTeardown": TestReportTeardown,
  "TestReportTeardownAction": TestReportTeardownAction,
  "TestReportTest": TestReportTest,
  "TestReportTestAction": TestReportTestAction,
  "TestReportActionResult": TestReportActionResult,
  "TestReportParticipantType": TestReportParticipantType,
  "TestReportResult": TestReportResult,
  "TestReportStatus": TestReportStatus,
  "TestScript": TestScript,
  "TestScriptDestination": TestScriptDestination,
  "TestScriptFixture": TestScriptFixture,
  "TestScriptMetadata": TestScriptMetadata,
  "TestScriptMetadataCapability": TestScriptMetadataCapability,
  "TestScriptMetadataLink": TestScriptMetadataLink,
  "TestScriptOrigin": TestScriptOrigin,
  "TestScriptSetup": TestScriptSetup,
  "TestScriptSetupAction": TestScriptSetupAction,
  "TestScriptSetupActionAssert": TestScriptSetupActionAssert,
  "TestScriptSetupActionOperation": TestScriptSetupActionOperation,
  "TestScriptSetupActionOperationRequestHeader": TestScriptSetupActionOperationRequestHeader,
  "TestScriptTeardown": TestScriptTeardown,
  "TestScriptTeardownAction": TestScriptTeardownAction,
  "TestScriptTest": TestScriptTest,
  "TestScriptTestAction": TestScriptTestAction,
  "TestScriptVariable": TestScriptVariable,
  "TestScriptRequestMethodCode": TestScriptRequestMethodCode,
  "Timing": Timing,
  "TimingRepeat": TimingRepeat,
  "TriggerDefinition": TriggerDefinition,
  "TriggerType": TriggerType,
  "TypeDerivationRule": TypeDerivationRule,
  "TypeRestfulInteraction": TypeRestfulInteraction,
  "UDIEntryType": UDIEntryType,
  "UnitsOfTime": UnitsOfTime,
  "UsageContext": UsageContext,
  "Use": Use,
  "ValueSet": ValueSet,
  "ValueSetCompose": ValueSetCompose,
  "ValueSetComposeInclude": ValueSetComposeInclude,
  "ValueSetComposeIncludeConcept": ValueSetComposeIncludeConcept,
  "ValueSetComposeIncludeConceptDesignation": ValueSetComposeIncludeConceptDesignation,
  "ValueSetComposeIncludeFilter": ValueSetComposeIncludeFilter,
  "ValueSetExpansion": ValueSetExpansion,
  "ValueSetExpansionContains": ValueSetExpansionContains,
  "ValueSetExpansionParameter": ValueSetExpansionParameter,
  "VariableType": VariableType,
  "VerificationResult": VerificationResult,
  "VerificationResultAttestation": VerificationResultAttestation,
  "VerificationResultPrimarySource": VerificationResultPrimarySource,
  "VerificationResultValidator": VerificationResultValidator,
  "VisionBase": VisionBase,
  "VisionEyes": VisionEyes,
  "VisionPrescription": VisionPrescription,
  "VisionPrescriptionLensSpecification": VisionPrescriptionLensSpecification,
  "VisionPrescriptionLensSpecificationPrism": VisionPrescriptionLensSpecificationPrism,
  "VisionStatus": VisionStatus,
  "XPathUsageType": XPathUsageType,
  "PrimitiveBase64Binary": PrimitiveBase64Binary,
  "PrimitiveBoolean": PrimitiveBoolean,
  "PrimitiveCanonical": PrimitiveCanonical,
  "PrimitiveCode": PrimitiveCode,
  "PrimitiveDate": PrimitiveDate,
  "PrimitiveDateTime": PrimitiveDateTime,
  "PrimitiveDecimal": PrimitiveDecimal,
  "PrimitiveId": PrimitiveId,
  "PrimitiveInstant": PrimitiveInstant,
  "PrimitiveInteger": PrimitiveInteger,
  "PrimitiveMarkdown": PrimitiveMarkdown,
  "PrimitiveOid": PrimitiveOid,
  "PrimitivePositiveInt": PrimitivePositiveInt,
  "PrimitiveQuestion": PrimitiveQuestion,
  "PrimitiveString": PrimitiveString,
  "PrimitiveTime": PrimitiveTime,
  "PrimitiveUnsignedInt": PrimitiveUnsignedInt,
  "PrimitiveUri": PrimitiveUri,
  "PrimitiveUrl": PrimitiveUrl,
  "PrimitiveUuid": PrimitiveUuid,
  "PrimitiveXhtml": PrimitiveXhtml,
  "Type": Type
};

export const allTypeNames = [
  "Account",
  "AccountCoverage",
  "AccountGuarantor",
  "AccountStatus",
  "ActionCardinalityBehavior",
  "ActionConditionKind",
  "ActionGroupingBehavior",
  "ActionParticipantType",
  "ActionPrecheckBehavior",
  "ActionRelationshipType",
  "ActionRequiredBehavior",
  "ActionSelectionBehavior",
  "ActivityDefinition",
  "ActivityDefinitionDynamicValue",
  "ActivityDefinitionParticipant",
  "ActivityDefinitionKind",
  "ActivityParticipantType",
  "Address",
  "AddressType",
  "AddressUse",
  "AdministrativeGender",
  "AdverseEvent",
  "AdverseEventSuspectEntity",
  "AdverseEventSuspectEntityCausality",
  "AdverseEventActuality",
  "Age",
  "AggregationMode",
  "AllergyIntolerance",
  "AllergyIntoleranceReaction",
  "AllergyIntoleranceCategory",
  "AllergyIntoleranceCriticality",
  "AllergyIntoleranceSeverity",
  "AllergyIntoleranceType",
  "Annotation",
  "Appointment",
  "AppointmentParticipant",
  "AppointmentResponse",
  "AppointmentStatus",
  "AssertionDirectionType",
  "AssertionOperatorType",
  "AssertionResponseTypes",
  "Attachment",
  "AuditEvent",
  "AuditEventAgent",
  "AuditEventAgentNetwork",
  "AuditEventEntity",
  "AuditEventEntityDetail",
  "AuditEventSource",
  "AuditEventAction",
  "AuditEventAgentNetworkType",
  "AuditEventOutcome",
  "BackboneElement",
  "Basic",
  "Binary",
  "BindingStrength",
  "BiologicallyDerivedProduct",
  "BiologicallyDerivedProductCollection",
  "BiologicallyDerivedProductManipulation",
  "BiologicallyDerivedProductProcessing",
  "BiologicallyDerivedProductStorage",
  "BiologicallyDerivedProductCategory",
  "BiologicallyDerivedProductStatus",
  "BiologicallyDerivedProductStorageScale",
  "BodyStructure",
  "Bundle",
  "BundleEntry",
  "BundleEntryRequest",
  "BundleEntryResponse",
  "BundleEntrySearch",
  "BundleLink",
  "BundleType",
  "CapabilityStatement",
  "CapabilityStatementDocument",
  "CapabilityStatementImplementation",
  "CapabilityStatementMessaging",
  "CapabilityStatementMessagingEndpoint",
  "CapabilityStatementMessagingSupportedMessage",
  "CapabilityStatementRest",
  "CapabilityStatementRestInteraction",
  "CapabilityStatementRestResource",
  "CapabilityStatementRestResourceInteraction",
  "CapabilityStatementRestResourceOperation",
  "CapabilityStatementRestResourceSearchParam",
  "CapabilityStatementRestSecurity",
  "CapabilityStatementSoftware",
  "CapabilityStatementKind",
  "CarePlan",
  "CarePlanActivity",
  "CarePlanActivityDetail",
  "CarePlanActivityKind",
  "CarePlanActivityStatus",
  "CarePlanIntent",
  "CarePlanStatus",
  "CareTeam",
  "CareTeamParticipant",
  "CareTeamStatus",
  "CatalogEntry",
  "CatalogEntryRelatedEntry",
  "CatalogEntryRelationType",
  "ChargeItem",
  "ChargeItemPerformer",
  "ChargeItemDefinition",
  "ChargeItemDefinitionApplicability",
  "ChargeItemDefinitionPropertyGroup",
  "ChargeItemDefinitionPropertyGroupPriceComponent",
  "ChargeItemDefinitionPriceComponentType",
  "ChargeItemStatus",
  "Claim",
  "ClaimAccident",
  "ClaimCareTeam",
  "ClaimDiagnosis",
  "ClaimInsurance",
  "ClaimItem",
  "ClaimItemDetail",
  "ClaimItemDetailSubDetail",
  "ClaimPayee",
  "ClaimProcedure",
  "ClaimRelated",
  "ClaimSupportingInfo",
  "ClaimResponse",
  "ClaimResponseAddItem",
  "ClaimResponseAddItemDetail",
  "ClaimResponseAddItemDetailSubDetail",
  "ClaimResponseError",
  "ClaimResponseInsurance",
  "ClaimResponseItem",
  "ClaimResponseItemAdjudication",
  "ClaimResponseItemDetail",
  "ClaimResponseItemDetailSubDetail",
  "ClaimResponsePayment",
  "ClaimResponseProcessNote",
  "ClaimResponseTotal",
  "ClaimResponseStatus",
  "ClaimStatus",
  "ClinicalImpression",
  "ClinicalImpressionFinding",
  "ClinicalImpressionInvestigation",
  "ClinicalImpressionStatus",
  "CodeSearchSupport",
  "CodeSystem",
  "CodeSystemConcept",
  "CodeSystemConceptDesignation",
  "CodeSystemConceptProperty",
  "CodeSystemFilter",
  "CodeSystemProperty",
  "CodeSystemContentMode",
  "CodeSystemHierarchyMeaning",
  "CodeableConcept",
  "Coding",
  "Communication",
  "CommunicationPayload",
  "CommunicationPriority",
  "CommunicationRequest",
  "CommunicationRequestPayload",
  "CommunicationRequestStatus",
  "CommunicationStatus",
  "CompartmentCode",
  "CompartmentDefinition",
  "CompartmentDefinitionResource",
  "CompartmentType",
  "Composition",
  "CompositionAttester",
  "CompositionEvent",
  "CompositionRelatesTo",
  "CompositionSection",
  "CompositionAttestationMode",
  "CompositionStatus",
  "ConceptMap",
  "ConceptMapGroup",
  "ConceptMapGroupElement",
  "ConceptMapGroupElementTarget",
  "ConceptMapGroupElementTargetDependsOn",
  "ConceptMapGroupUnmapped",
  "ConceptMapEquivalence",
  "ConceptMapGroupUnmappedMode",
  "Condition",
  "ConditionEvidence",
  "ConditionStage",
  "ConditionalDeleteStatus",
  "ConditionalReadStatus",
  "Consent",
  "ConsentPolicy",
  "ConsentProvision",
  "ConsentProvisionActor",
  "ConsentProvisionData",
  "ConsentVerification",
  "ConsentDataMeaning",
  "ConsentProvisionType",
  "ConsentState",
  "ConstraintSeverity",
  "ContactDetail",
  "ContactPoint",
  "ContactPointSystem",
  "ContactPointUse",
  "Contract",
  "ContractContentDefinition",
  "ContractFriendly",
  "ContractLegal",
  "ContractRule",
  "ContractSigner",
  "ContractTerm",
  "ContractTermAction",
  "ContractTermActionSubject",
  "ContractTermAsset",
  "ContractTermAssetContext",
  "ContractTermAssetValuedItem",
  "ContractTermOffer",
  "ContractTermOfferAnswer",
  "ContractTermOfferParty",
  "ContractTermSecurityLabel",
  "ContractPublicationStatus",
  "ContractStatus",
  "Contributor",
  "ContributorType",
  "Count",
  "Coverage",
  "CoverageClass",
  "CoverageCostToBeneficiary",
  "CoverageCostToBeneficiaryException",
  "CoverageEligibilityRequest",
  "CoverageEligibilityRequestInsurance",
  "CoverageEligibilityRequestItem",
  "CoverageEligibilityRequestItemDiagnosis",
  "CoverageEligibilityRequestSupportingInfo",
  "CoverageEligibilityResponse",
  "CoverageEligibilityResponseError",
  "CoverageEligibilityResponseInsurance",
  "CoverageEligibilityResponseInsuranceItem",
  "CoverageEligibilityResponseInsuranceItemBenefit",
  "CoverageStatus",
  "CurrencyCode",
  "DataRequirement",
  "DataRequirementCodeFilter",
  "DataRequirementDateFilter",
  "DataRequirementSort",
  "DayOfWeek",
  "DaysOfWeek",
  "DetectedIssue",
  "DetectedIssueEvidence",
  "DetectedIssueMitigation",
  "DetectedIssueSeverity",
  "DetectedIssueStatus",
  "Device",
  "DeviceDeviceName",
  "DeviceProperty",
  "DeviceSpecialization",
  "DeviceUdiCarrier",
  "DeviceVersion",
  "DeviceDefinition",
  "DeviceDefinitionCapability",
  "DeviceDefinitionDeviceName",
  "DeviceDefinitionMaterial",
  "DeviceDefinitionProperty",
  "DeviceDefinitionSpecialization",
  "DeviceDefinitionUdiDeviceIdentifier",
  "DeviceMetric",
  "DeviceMetricCalibration",
  "DeviceMetricCalibrationState",
  "DeviceMetricCalibrationType",
  "DeviceMetricCategory",
  "DeviceMetricColor",
  "DeviceMetricOperationalStatus",
  "DeviceNameType",
  "DeviceRequest",
  "DeviceRequestParameter",
  "DeviceRequestStatus",
  "DeviceUseStatement",
  "DeviceUseStatementStatus",
  "DiagnosticReport",
  "DiagnosticReportMedia",
  "DiagnosticReportStatus",
  "DiscriminatorType",
  "Distance",
  "DocumentConfidentiality",
  "DocumentManifest",
  "DocumentManifestRelated",
  "DocumentMode",
  "DocumentReference",
  "DocumentReferenceContent",
  "DocumentReferenceContext",
  "DocumentReferenceRelatesTo",
  "DocumentReferenceStatus",
  "DocumentRelationshipType",
  "DomainResource",
  "Dosage",
  "DosageDoseAndRate",
  "Duration",
  "EffectEvidenceSynthesis",
  "EffectEvidenceSynthesisCertainty",
  "EffectEvidenceSynthesisCertaintyCertaintySubcomponent",
  "EffectEvidenceSynthesisEffectEstimate",
  "EffectEvidenceSynthesisEffectEstimatePrecisionEstimate",
  "EffectEvidenceSynthesisResultsByExposure",
  "EffectEvidenceSynthesisSampleSize",
  "Element",
  "ElementDefinition",
  "ElementDefinitionBase",
  "ElementDefinitionBinding",
  "ElementDefinitionConstraint",
  "ElementDefinitionExample",
  "ElementDefinitionMapping",
  "ElementDefinitionSlicing",
  "ElementDefinitionSlicingDiscriminator",
  "ElementDefinitionType",
  "EligibilityRequestPurpose",
  "EligibilityRequestStatus",
  "EligibilityResponsePurpose",
  "EligibilityResponseStatus",
  "EnableWhenBehavior",
  "Encounter",
  "EncounterClassHistory",
  "EncounterDiagnosis",
  "EncounterHospitalization",
  "EncounterLocation",
  "EncounterParticipant",
  "EncounterStatusHistory",
  "EncounterLocationStatus",
  "EncounterStatus",
  "Endpoint",
  "EndpointStatus",
  "EnrollmentRequest",
  "EnrollmentRequestStatus",
  "EnrollmentResponse",
  "EnrollmentResponseStatus",
  "EpisodeOfCare",
  "EpisodeOfCareDiagnosis",
  "EpisodeOfCareStatusHistory",
  "EpisodeOfCareStatus",
  "EventCapabilityMode",
  "EventDefinition",
  "EventTiming",
  "Evidence",
  "EvidenceVariable",
  "EvidenceVariableCharacteristic",
  "EvidenceVariableType",
  "ExampleScenario",
  "ExampleScenarioActor",
  "ExampleScenarioInstance",
  "ExampleScenarioInstanceContainedInstance",
  "ExampleScenarioInstanceVersion",
  "ExampleScenarioProcess",
  "ExampleScenarioProcessStep",
  "ExampleScenarioProcessStepAlternative",
  "ExampleScenarioProcessStepOperation",
  "ExampleScenarioActorType",
  "ExplanationOfBenefit",
  "ExplanationOfBenefitAccident",
  "ExplanationOfBenefitAddItem",
  "ExplanationOfBenefitAddItemDetail",
  "ExplanationOfBenefitAddItemDetailSubDetail",
  "ExplanationOfBenefitBenefitBalance",
  "ExplanationOfBenefitBenefitBalanceFinancial",
  "ExplanationOfBenefitCareTeam",
  "ExplanationOfBenefitDiagnosis",
  "ExplanationOfBenefitInsurance",
  "ExplanationOfBenefitItem",
  "ExplanationOfBenefitItemAdjudication",
  "ExplanationOfBenefitItemDetail",
  "ExplanationOfBenefitItemDetailSubDetail",
  "ExplanationOfBenefitPayee",
  "ExplanationOfBenefitPayment",
  "ExplanationOfBenefitProcedure",
  "ExplanationOfBenefitProcessNote",
  "ExplanationOfBenefitRelated",
  "ExplanationOfBenefitSupportingInfo",
  "ExplanationOfBenefitTotal",
  "ExplanationOfBenefitStatus",
  "ExposureState",
  "Expression",
  "Extension",
  "ExtensionContextType",
  "FHIRAllTypes",
  "FHIRDefinedType",
  "FHIRDeviceStatus",
  "FHIRResourceType",
  "FHIRSubstanceStatus",
  "FHIRVersion",
  "FamilyHistoryStatus",
  "FamilyMemberHistory",
  "FamilyMemberHistoryCondition",
  "FilterOperator",
  "Flag",
  "FlagStatus",
  "Goal",
  "GoalTarget",
  "GoalLifecycleStatus",
  "GraphCompartmentRule",
  "GraphCompartmentUse",
  "GraphDefinition",
  "GraphDefinitionLink",
  "GraphDefinitionLinkTarget",
  "GraphDefinitionLinkTargetCompartment",
  "Group",
  "GroupCharacteristic",
  "GroupMember",
  "GroupMeasure",
  "GroupType",
  "GuidanceResponse",
  "GuidanceResponseStatus",
  "GuidePageGeneration",
  "GuideParameterCode",
  "HTTPVerb",
  "HealthcareService",
  "HealthcareServiceAvailableTime",
  "HealthcareServiceEligibility",
  "HealthcareServiceNotAvailable",
  "HumanName",
  "Identifier",
  "IdentifierUse",
  "IdentityAssuranceLevel",
  "ImagingStudy",
  "ImagingStudySeries",
  "ImagingStudySeriesInstance",
  "ImagingStudySeriesPerformer",
  "ImagingStudyStatus",
  "Immunization",
  "ImmunizationEducation",
  "ImmunizationPerformer",
  "ImmunizationProtocolApplied",
  "ImmunizationReaction",
  "ImmunizationEvaluation",
  "ImmunizationEvaluationStatus",
  "ImmunizationRecommendation",
  "ImmunizationRecommendationRecommendation",
  "ImmunizationRecommendationRecommendationDateCriterion",
  "ImmunizationStatus",
  "ImplementationGuide",
  "ImplementationGuideDefinition",
  "ImplementationGuideDefinitionGrouping",
  "ImplementationGuideDefinitionPage",
  "ImplementationGuideDefinitionParameter",
  "ImplementationGuideDefinitionResource",
  "ImplementationGuideDefinitionTemplate",
  "ImplementationGuideDependsOn",
  "ImplementationGuideGlobal",
  "ImplementationGuideManifest",
  "ImplementationGuideManifestPage",
  "ImplementationGuideManifestResource",
  "InsurancePlan",
  "InsurancePlanContact",
  "InsurancePlanCoverage",
  "InsurancePlanCoverageBenefit",
  "InsurancePlanCoverageBenefitLimit",
  "InsurancePlanPlan",
  "InsurancePlanPlanGeneralCost",
  "InsurancePlanPlanSpecificCost",
  "InsurancePlanPlanSpecificCostBenefit",
  "InsurancePlanPlanSpecificCostBenefitCost",
  "Invoice",
  "InvoiceLineItem",
  "InvoiceLineItemPriceComponent",
  "InvoiceParticipant",
  "InvoicePriceComponentType",
  "InvoiceStatus",
  "IssueSeverity",
  "IssueType",
  "Library",
  "LinkType",
  "Linkage",
  "LinkageItem",
  "LinkageType",
  "List",
  "ListEntry",
  "ListMode",
  "ListStatus",
  "Location",
  "LocationHoursOfOperation",
  "LocationPosition",
  "LocationMode",
  "LocationStatus",
  "MarketingStatus",
  "Measure",
  "MeasureGroup",
  "MeasureGroupPopulation",
  "MeasureGroupStratifier",
  "MeasureGroupStratifierComponent",
  "MeasureSupplementalData",
  "MeasureReport",
  "MeasureReportGroup",
  "MeasureReportGroupPopulation",
  "MeasureReportGroupStratifier",
  "MeasureReportGroupStratifierStratum",
  "MeasureReportGroupStratifierStratumComponent",
  "MeasureReportGroupStratifierStratumPopulation",
  "MeasureReportStatus",
  "MeasureReportType",
  "Media",
  "MediaStatus",
  "Medication",
  "MedicationBatch",
  "MedicationIngredient",
  "MedicationAdministration",
  "MedicationAdministrationDosage",
  "MedicationAdministrationPerformer",
  "MedicationAdministrationStatus",
  "MedicationDispense",
  "MedicationDispensePerformer",
  "MedicationDispenseSubstitution",
  "MedicationDispenseStatus",
  "MedicationKnowledge",
  "MedicationKnowledgeAdministrationGuidelines",
  "MedicationKnowledgeAdministrationGuidelinesDosage",
  "MedicationKnowledgeAdministrationGuidelinesPatientCharacteristics",
  "MedicationKnowledgeCost",
  "MedicationKnowledgeDrugCharacteristic",
  "MedicationKnowledgeIngredient",
  "MedicationKnowledgeKinetics",
  "MedicationKnowledgeMedicineClassification",
  "MedicationKnowledgeMonitoringProgram",
  "MedicationKnowledgeMonograph",
  "MedicationKnowledgePackaging",
  "MedicationKnowledgeRegulatory",
  "MedicationKnowledgeRegulatoryMaxDispense",
  "MedicationKnowledgeRegulatorySchedule",
  "MedicationKnowledgeRegulatorySubstitution",
  "MedicationKnowledgeRelatedMedicationKnowledge",
  "MedicationKnowledgeStatus",
  "MedicationRequest",
  "MedicationRequestDispenseRequest",
  "MedicationRequestDispenseRequestInitialFill",
  "MedicationRequestSubstitution",
  "MedicationRequestIntent",
  "MedicationRequestPriority",
  "MedicationRequestStatus",
  "MedicationStatement",
  "MedicationStatementStatus",
  "MedicationStatus",
  "MedicinalProduct",
  "MedicinalProductManufacturingBusinessOperation",
  "MedicinalProductName",
  "MedicinalProductNameCountryLanguage",
  "MedicinalProductNameNamePart",
  "MedicinalProductSpecialDesignation",
  "MedicinalProductAuthorization",
  "MedicinalProductAuthorizationJurisdictionalAuthorization",
  "MedicinalProductAuthorizationProcedure",
  "MedicinalProductContraindication",
  "MedicinalProductContraindicationOtherTherapy",
  "MedicinalProductIndication",
  "MedicinalProductIndicationOtherTherapy",
  "MedicinalProductIngredient",
  "MedicinalProductIngredientSpecifiedSubstance",
  "MedicinalProductIngredientSpecifiedSubstanceStrength",
  "MedicinalProductIngredientSpecifiedSubstanceStrengthReferenceStrength",
  "MedicinalProductIngredientSubstance",
  "MedicinalProductInteraction",
  "MedicinalProductInteractionInteractant",
  "MedicinalProductManufactured",
  "MedicinalProductPackaged",
  "MedicinalProductPackagedBatchIdentifier",
  "MedicinalProductPackagedPackageItem",
  "MedicinalProductPharmaceutical",
  "MedicinalProductPharmaceuticalCharacteristics",
  "MedicinalProductPharmaceuticalRouteOfAdministration",
  "MedicinalProductPharmaceuticalRouteOfAdministrationTargetSpecies",
  "MedicinalProductPharmaceuticalRouteOfAdministrationTargetSpeciesWithdrawalPeriod",
  "MedicinalProductUndesirableEffect",
  "MessageDefinition",
  "MessageDefinitionAllowedResponse",
  "MessageDefinitionFocus",
  "MessageHeader",
  "MessageHeaderDestination",
  "MessageHeaderResponse",
  "MessageHeaderSource",
  "MessageSignificanceCategory",
  "MessageheaderResponseRequest",
  "Meta",
  "MimeType",
  "MolecularSequence",
  "MolecularSequenceQuality",
  "MolecularSequenceQualityRoc",
  "MolecularSequenceReferenceSeq",
  "MolecularSequenceRepository",
  "MolecularSequenceStructureVariant",
  "MolecularSequenceStructureVariantInner",
  "MolecularSequenceStructureVariantOuter",
  "MolecularSequenceVariant",
  "Money",
  "MoneyQuantity",
  "NameUse",
  "NamingSystem",
  "NamingSystemUniqueId",
  "NamingSystemIdentifierType",
  "NamingSystemType",
  "Narrative",
  "NarrativeStatus",
  "NoteType",
  "NutritiionOrderIntent",
  "NutritionOrder",
  "NutritionOrderEnteralFormula",
  "NutritionOrderEnteralFormulaAdministration",
  "NutritionOrderOralDiet",
  "NutritionOrderOralDietNutrient",
  "NutritionOrderOralDietTexture",
  "NutritionOrderSupplement",
  "NutritionOrderStatus",
  "Observation",
  "ObservationComponent",
  "ObservationReferenceRange",
  "ObservationDataType",
  "ObservationDefinition",
  "ObservationDefinitionQualifiedInterval",
  "ObservationDefinitionQuantitativeDetails",
  "ObservationRangeCategory",
  "ObservationStatus",
  "OperationDefinition",
  "OperationDefinitionOverload",
  "OperationDefinitionParameter",
  "OperationDefinitionParameterBinding",
  "OperationDefinitionParameterReferencedFrom",
  "OperationKind",
  "OperationOutcome",
  "OperationOutcomeIssue",
  "OperationParameterUse",
  "Organization",
  "OrganizationContact",
  "OrganizationAffiliation",
  "OrientationType",
  "ParameterDefinition",
  "ParameterUse",
  "Parameters",
  "ParametersParameter",
  "ParticipantRequired",
  "ParticipantStatus",
  "ParticipationStatus",
  "Patient",
  "PatientCommunication",
  "PatientContact",
  "PatientLink",
  "PaymentNotice",
  "PaymentNoticeStatus",
  "PaymentReconciliation",
  "PaymentReconciliationDetail",
  "PaymentReconciliationProcessNote",
  "PaymentReconciliationStatus",
  "Period",
  "Person",
  "PersonLink",
  "PlanDefinition",
  "PlanDefinitionAction",
  "PlanDefinitionActionCondition",
  "PlanDefinitionActionDynamicValue",
  "PlanDefinitionActionParticipant",
  "PlanDefinitionActionRelatedAction",
  "PlanDefinitionGoal",
  "PlanDefinitionGoalTarget",
  "Population",
  "Practitioner",
  "PractitionerQualification",
  "PractitionerRole",
  "PractitionerRoleAvailableTime",
  "PractitionerRoleNotAvailable",
  "Procedure",
  "ProcedureFocalDevice",
  "ProcedurePerformer",
  "ProcedureStatus",
  "ProdCharacteristic",
  "ProductShelfLife",
  "PropertyRepresentation",
  "PropertyType",
  "Provenance",
  "ProvenanceAgent",
  "ProvenanceEntity",
  "ProvenanceEntityRole",
  "PublicationStatus",
  "QualityType",
  "Quantity",
  "QuantityComparator",
  "Questionnaire",
  "QuestionnaireItem",
  "QuestionnaireItemAnswerOption",
  "QuestionnaireItemEnableWhen",
  "QuestionnaireItemInitial",
  "QuestionnaireItemOperator",
  "QuestionnaireItemType",
  "QuestionnaireResponse",
  "QuestionnaireResponseItem",
  "QuestionnaireResponseItemAnswer",
  "QuestionnaireResponseStatus",
  "Range",
  "Ratio",
  "Reference",
  "ReferenceHandlingPolicy",
  "ReferenceVersionRules",
  "ReferredDocumentStatus",
  "RelatedArtifact",
  "RelatedArtifactType",
  "RelatedPerson",
  "RelatedPersonCommunication",
  "RemittanceOutcome",
  "RepositoryType",
  "RequestGroup",
  "RequestGroupAction",
  "RequestGroupActionCondition",
  "RequestGroupActionRelatedAction",
  "RequestIntent",
  "RequestPriority",
  "RequestStatus",
  "ResearchDefinition",
  "ResearchElementDefinition",
  "ResearchElementDefinitionCharacteristic",
  "ResearchElementType",
  "ResearchStudy",
  "ResearchStudyArm",
  "ResearchStudyObjective",
  "ResearchStudyStatus",
  "ResearchSubject",
  "ResearchSubjectStatus",
  "Resource",
  "ResourceType",
  "ResourceVersionPolicy",
  "ResponseType",
  "RestfulCapabilityMode",
  "RiskAssessment",
  "RiskAssessmentPrediction",
  "RiskAssessmentStatus",
  "RiskEvidenceSynthesis",
  "RiskEvidenceSynthesisCertainty",
  "RiskEvidenceSynthesisCertaintyCertaintySubcomponent",
  "RiskEvidenceSynthesisRiskEstimate",
  "RiskEvidenceSynthesisRiskEstimatePrecisionEstimate",
  "RiskEvidenceSynthesisSampleSize",
  "SPDXLicense",
  "SampledData",
  "Schedule",
  "SearchComparator",
  "SearchEntryMode",
  "SearchModifierCode",
  "SearchParamType",
  "SearchParameter",
  "SearchParameterComponent",
  "SectionMode",
  "SequenceType",
  "ServiceRequest",
  "ServiceRequestIntent",
  "ServiceRequestPriority",
  "ServiceRequestStatus",
  "Signature",
  "SimpleQuantity",
  "SlicingRules",
  "Slot",
  "SlotStatus",
  "SortDirection",
  "Specimen",
  "SpecimenCollection",
  "SpecimenContainer",
  "SpecimenProcessing",
  "SpecimenContainedPreference",
  "SpecimenDefinition",
  "SpecimenDefinitionTypeTested",
  "SpecimenDefinitionTypeTestedContainer",
  "SpecimenDefinitionTypeTestedContainerAdditive",
  "SpecimenDefinitionTypeTestedHandling",
  "SpecimenStatus",
  "Status",
  "StrandType",
  "StructureDefinition",
  "StructureDefinitionContext",
  "StructureDefinitionDifferential",
  "StructureDefinitionMapping",
  "StructureDefinitionSnapshot",
  "StructureDefinitionKind",
  "StructureMap",
  "StructureMapGroup",
  "StructureMapGroupInput",
  "StructureMapGroupRule",
  "StructureMapGroupRuleDependent",
  "StructureMapGroupRuleSource",
  "StructureMapGroupRuleTarget",
  "StructureMapGroupRuleTargetParameter",
  "StructureMapStructure",
  "StructureMapContextType",
  "StructureMapGroupTypeMode",
  "StructureMapInputMode",
  "StructureMapModelMode",
  "StructureMapSourceListMode",
  "StructureMapTargetListMode",
  "StructureMapTransform",
  "Subscription",
  "SubscriptionChannel",
  "SubscriptionChannelType",
  "SubscriptionStatus",
  "Substance",
  "SubstanceIngredient",
  "SubstanceInstance",
  "SubstanceAmount",
  "SubstanceAmountReferenceRange",
  "SubstanceNucleicAcid",
  "SubstanceNucleicAcidSubunit",
  "SubstanceNucleicAcidSubunitLinkage",
  "SubstanceNucleicAcidSubunitSugar",
  "SubstancePolymer",
  "SubstancePolymerMonomerSet",
  "SubstancePolymerMonomerSetStartingMaterial",
  "SubstancePolymerRepeat",
  "SubstancePolymerRepeatRepeatUnit",
  "SubstancePolymerRepeatRepeatUnitDegreeOfPolymerisation",
  "SubstancePolymerRepeatRepeatUnitStructuralRepresentation",
  "SubstanceProtein",
  "SubstanceProteinSubunit",
  "SubstanceReferenceInformation",
  "SubstanceReferenceInformationClassification",
  "SubstanceReferenceInformationGene",
  "SubstanceReferenceInformationGeneElement",
  "SubstanceReferenceInformationTarget",
  "SubstanceSourceMaterial",
  "SubstanceSourceMaterialFractionDescription",
  "SubstanceSourceMaterialOrganism",
  "SubstanceSourceMaterialOrganismAuthor",
  "SubstanceSourceMaterialOrganismHybrid",
  "SubstanceSourceMaterialOrganismOrganismGeneral",
  "SubstanceSourceMaterialPartDescription",
  "SubstanceSpecification",
  "SubstanceSpecificationCode",
  "SubstanceSpecificationMoiety",
  "SubstanceSpecificationName",
  "SubstanceSpecificationNameOfficial",
  "SubstanceSpecificationProperty",
  "SubstanceSpecificationRelationship",
  "SubstanceSpecificationStructure",
  "SubstanceSpecificationStructureIsotope",
  "SubstanceSpecificationStructureIsotopeMolecularWeight",
  "SubstanceSpecificationStructureRepresentation",
  "SupplyDelivery",
  "SupplyDeliverySuppliedItem",
  "SupplyDeliveryStatus",
  "SupplyRequest",
  "SupplyRequestParameter",
  "SupplyRequestStatus",
  "SystemRestfulInteraction",
  "Task",
  "TaskInput",
  "TaskOutput",
  "TaskRestriction",
  "TaskIntent",
  "TaskPriority",
  "TaskStatus",
  "TerminologyCapabilities",
  "TerminologyCapabilitiesClosure",
  "TerminologyCapabilitiesCodeSystem",
  "TerminologyCapabilitiesCodeSystemVersion",
  "TerminologyCapabilitiesCodeSystemVersionFilter",
  "TerminologyCapabilitiesExpansion",
  "TerminologyCapabilitiesExpansionParameter",
  "TerminologyCapabilitiesImplementation",
  "TerminologyCapabilitiesSoftware",
  "TerminologyCapabilitiesTranslation",
  "TerminologyCapabilitiesValidateCode",
  "TestReport",
  "TestReportParticipant",
  "TestReportSetup",
  "TestReportSetupAction",
  "TestReportSetupActionAssert",
  "TestReportSetupActionOperation",
  "TestReportTeardown",
  "TestReportTeardownAction",
  "TestReportTest",
  "TestReportTestAction",
  "TestReportActionResult",
  "TestReportParticipantType",
  "TestReportResult",
  "TestReportStatus",
  "TestScript",
  "TestScriptDestination",
  "TestScriptFixture",
  "TestScriptMetadata",
  "TestScriptMetadataCapability",
  "TestScriptMetadataLink",
  "TestScriptOrigin",
  "TestScriptSetup",
  "TestScriptSetupAction",
  "TestScriptSetupActionAssert",
  "TestScriptSetupActionOperation",
  "TestScriptSetupActionOperationRequestHeader",
  "TestScriptTeardown",
  "TestScriptTeardownAction",
  "TestScriptTest",
  "TestScriptTestAction",
  "TestScriptVariable",
  "TestScriptRequestMethodCode",
  "Timing",
  "TimingRepeat",
  "TriggerDefinition",
  "TriggerType",
  "TypeDerivationRule",
  "TypeRestfulInteraction",
  "UDIEntryType",
  "UnitsOfTime",
  "UsageContext",
  "Use",
  "ValueSet",
  "ValueSetCompose",
  "ValueSetComposeInclude",
  "ValueSetComposeIncludeConcept",
  "ValueSetComposeIncludeConceptDesignation",
  "ValueSetComposeIncludeFilter",
  "ValueSetExpansion",
  "ValueSetExpansionContains",
  "ValueSetExpansionParameter",
  "VariableType",
  "VerificationResult",
  "VerificationResultAttestation",
  "VerificationResultPrimarySource",
  "VerificationResultValidator",
  "VisionBase",
  "VisionEyes",
  "VisionPrescription",
  "VisionPrescriptionLensSpecification",
  "VisionPrescriptionLensSpecificationPrism",
  "VisionStatus",
  "XPathUsageType",
  "PrimitiveBase64Binary",
  "PrimitiveBoolean",
  "PrimitiveCanonical",
  "PrimitiveCode",
  "PrimitiveDate",
  "PrimitiveDateTime",
  "PrimitiveDecimal",
  "PrimitiveId",
  "PrimitiveInstant",
  "PrimitiveInteger",
  "PrimitiveMarkdown",
  "PrimitiveOid",
  "PrimitivePositiveInt",
  "PrimitiveQuestion",
  "PrimitiveString",
  "PrimitiveTime",
  "PrimitiveUnsignedInt",
  "PrimitiveUri",
  "PrimitiveUrl",
  "PrimitiveUuid",
  "PrimitiveXhtml",
  "Type"
] as const;

type TypeNames = typeof allTypeNames;
export type TypeName = TypeNames[number];

export function lookupType(typeName: string): typeof Type | undefined {
  return typeMapping[typeName];
}
/* eslint-enable import/prefer-default-export, import/no-cycle */
